//! Bulk operations for Candidate entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateCandidateDto;
use crate::application::service::CandidateService;
use crate::domain::entity::Candidate;

/// Bulk operation handler for Candidate entities.
///
/// Wraps `CandidateService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type CandidateBulkService = GenericBulkService<Candidate, CreateCandidateDto, CandidateService>;

// <<< CUSTOM
// END CUSTOM
