//! Bulk operations for Interview entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateInterviewDto;
use crate::application::service::InterviewService;
use crate::domain::entity::Interview;

/// Bulk operation handler for Interview entities.
///
/// Wraps `InterviewService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type InterviewBulkService = GenericBulkService<Interview, CreateInterviewDto, InterviewService>;

// <<< CUSTOM
// END CUSTOM
