//! Bulk operations for JobOffer entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateJobOfferDto;
use crate::application::service::JobOfferService;
use crate::domain::entity::JobOffer;

/// Bulk operation handler for JobOffer entities.
///
/// Wraps `JobOfferService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type JobOfferBulkService = GenericBulkService<JobOffer, CreateJobOfferDto, JobOfferService>;

// <<< CUSTOM
// END CUSTOM
