//! Bulk operations for JobApplication entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateJobApplicationDto;
use crate::application::service::JobApplicationService;
use crate::domain::entity::JobApplication;

/// Bulk operation handler for JobApplication entities.
///
/// Wraps `JobApplicationService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type JobApplicationBulkService = GenericBulkService<JobApplication, CreateJobApplicationDto, JobApplicationService>;

// <<< CUSTOM
// END CUSTOM
