//! Bulk operations
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod candidate_bulk;
pub mod interview_bulk;
pub mod job_application_bulk;
pub mod job_offer_bulk;
pub mod job_requisition_bulk;

pub use candidate_bulk::CandidateBulkService;
pub use interview_bulk::InterviewBulkService;
pub use job_application_bulk::JobApplicationBulkService;
pub use job_offer_bulk::JobOfferBulkService;
pub use job_requisition_bulk::JobRequisitionBulkService;

// <<< CUSTOM
// END CUSTOM
