//! Candidate DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Candidate;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::CandidateSource;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Candidate
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateCandidateDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "first_name")]
    pub first_name: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "last_name")]
    pub last_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source: Option<CandidateSource>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "current_employer")]
    pub current_employer: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "resume_url")]
    pub resume_url: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Candidate
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateCandidateDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "first_name")]
    pub first_name: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "last_name")]
    pub last_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source: Option<CandidateSource>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "current_employer")]
    pub current_employer: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "resume_url")]
    pub resume_url: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Candidate
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchCandidateDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "first_name")]
    pub first_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "last_name")]
    pub last_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source: Option<CandidateSource>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "current_employer")]
    pub current_employer: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "resume_url")]
    pub resume_url: Option<String>,
}

impl PatchCandidateDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.first_name.is_some() || self.last_name.is_some() || self.email.is_some() || self.phone.is_some() || self.source.is_some() || self.current_employer.is_some() || self.resume_url.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Candidate entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CandidateResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub first_name: String,
    pub last_name: Option<String>,
    pub email: Option<String>,
    pub phone: Option<String>,
    pub source: Option<CandidateSource>,
    pub current_employer: Option<String>,
    pub resume_url: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Candidate entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CandidateListResponseDto {
    /// List of items
    pub items: Vec<CandidateResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl CandidateListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<CandidateResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CandidateSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub first_name: String,
    pub last_name: Option<String>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Candidate> for CandidateResponseDto {
    fn from(entity: Candidate) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            first_name: entity.first_name,
            last_name: entity.last_name,
            email: entity.email,
            phone: entity.phone,
            source: entity.source,
            current_employer: entity.current_employer,
            resume_url: entity.resume_url,
            metadata: entity.metadata,
        }
    }
}

impl From<Candidate> for CandidateSummaryDto {
    fn from(entity: Candidate) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            first_name: entity.first_name,
            last_name: entity.last_name,
            created_at,
        }
    }
}

impl From<CreateCandidateDto> for Candidate {
    fn from(dto: CreateCandidateDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            first_name: dto.first_name,
            last_name: dto.last_name,
            email: dto.email,
            phone: dto.phone,
            source: dto.source,
            current_employer: dto.current_employer,
            resume_url: dto.resume_url,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Candidate> for CandidateResponseDto {
    fn from(entity: &Candidate) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            first_name: entity.first_name.clone(),
            last_name: entity.last_name.clone(),
            email: entity.email.clone(),
            phone: entity.phone.clone(),
            source: entity.source.clone(),
            current_employer: entity.current_employer.clone(),
            resume_url: entity.resume_url.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateCandidateDto> for Candidate {
    fn from_create_dto(dto: CreateCandidateDto) -> backbone_core::ServiceResult<Self> {
        Ok(Candidate::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateCandidateDto> for Candidate {
    fn apply_update(mut self, dto: UpdateCandidateDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.first_name = dto.first_name;
        self.last_name = dto.last_name;
        self.email = dto.email;
        self.phone = dto.phone;
        self.source = dto.source;
        self.current_employer = dto.current_employer;
        self.resume_url = dto.resume_url;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Candidate here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

