//! Interview DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Interview;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::InterviewStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Interview
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateInterviewDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "application_id")]
    pub application_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "interviewer_id")]
    pub interviewer_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "scheduled_at")]
    pub scheduled_at: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub round: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "interview_format")]
    pub interview_format: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rating: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub feedback: Option<String>,
    pub status: InterviewStatus,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Interview
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateInterviewDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "application_id")]
    pub application_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "interviewer_id")]
    pub interviewer_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "scheduled_at")]
    pub scheduled_at: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub round: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "interview_format")]
    pub interview_format: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rating: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub feedback: Option<String>,
    pub status: InterviewStatus,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Interview
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchInterviewDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "application_id")]
    pub application_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "interviewer_id")]
    pub interviewer_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "scheduled_at")]
    pub scheduled_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub round: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "interview_format")]
    pub interview_format: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rating: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub feedback: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<InterviewStatus>,
}

impl PatchInterviewDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.application_id.is_some() || self.interviewer_id.is_some() || self.scheduled_at.is_some() || self.round.is_some() || self.interview_format.is_some() || self.rating.is_some() || self.feedback.is_some() || self.status.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Interview entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct InterviewResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub application_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub interviewer_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub scheduled_at: DateTime<Utc>,
    pub round: Option<i32>,
    pub interview_format: Option<String>,
    pub rating: Option<i32>,
    pub feedback: Option<String>,
    pub status: InterviewStatus,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Interview entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct InterviewListResponseDto {
    /// List of items
    pub items: Vec<InterviewResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl InterviewListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<InterviewResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct InterviewSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub application_id: Uuid,
    pub interviewer_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Interview> for InterviewResponseDto {
    fn from(entity: Interview) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            application_id: entity.application_id,
            interviewer_id: entity.interviewer_id,
            scheduled_at: entity.scheduled_at,
            round: entity.round,
            interview_format: entity.interview_format,
            rating: entity.rating,
            feedback: entity.feedback,
            status: entity.status,
            metadata: entity.metadata,
        }
    }
}

impl From<Interview> for InterviewSummaryDto {
    fn from(entity: Interview) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            application_id: entity.application_id,
            interviewer_id: entity.interviewer_id,
            created_at,
        }
    }
}

impl From<CreateInterviewDto> for Interview {
    fn from(dto: CreateInterviewDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            application_id: dto.application_id,
            interviewer_id: dto.interviewer_id,
            scheduled_at: dto.scheduled_at,
            round: dto.round,
            interview_format: dto.interview_format,
            rating: dto.rating,
            feedback: dto.feedback,
            status: dto.status,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Interview> for InterviewResponseDto {
    fn from(entity: &Interview) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            application_id: entity.application_id.clone(),
            interviewer_id: entity.interviewer_id.clone(),
            scheduled_at: entity.scheduled_at.clone(),
            round: entity.round.clone(),
            interview_format: entity.interview_format.clone(),
            rating: entity.rating.clone(),
            feedback: entity.feedback.clone(),
            status: entity.status.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateInterviewDto> for Interview {
    fn from_create_dto(dto: CreateInterviewDto) -> backbone_core::ServiceResult<Self> {
        Ok(Interview::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateInterviewDto> for Interview {
    fn apply_update(mut self, dto: UpdateInterviewDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.application_id = dto.application_id;
        self.interviewer_id = dto.interviewer_id;
        self.scheduled_at = dto.scheduled_at;
        self.round = dto.round;
        self.interview_format = dto.interview_format;
        self.rating = dto.rating;
        self.feedback = dto.feedback;
        self.status = dto.status;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Interview here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

