//! JobOffer DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::JobOffer;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::OfferStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new JobOffer
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateJobOfferDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "application_id")]
    pub application_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "proposed_salary")]
    pub proposed_salary: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "employment_type")]
    pub employment_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "letter_template_id")]
    pub letter_template_id: Option<Uuid>,
    pub status: OfferStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "offered_at")]
    pub offered_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "accepted_at")]
    pub accepted_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a JobOffer
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateJobOfferDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "application_id")]
    pub application_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "proposed_salary")]
    pub proposed_salary: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "employment_type")]
    pub employment_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "letter_template_id")]
    pub letter_template_id: Option<Uuid>,
    pub status: OfferStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "offered_at")]
    pub offered_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "accepted_at")]
    pub accepted_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a JobOffer
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchJobOfferDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "application_id")]
    pub application_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "proposed_salary")]
    pub proposed_salary: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "employment_type")]
    pub employment_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "letter_template_id")]
    pub letter_template_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<OfferStatus>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "offered_at")]
    pub offered_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "accepted_at")]
    pub accepted_at: Option<DateTime<Utc>>,
}

impl PatchJobOfferDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.application_id.is_some() || self.proposed_salary.is_some() || self.employment_type.is_some() || self.letter_template_id.is_some() || self.status.is_some() || self.offered_at.is_some() || self.accepted_at.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for JobOffer entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct JobOfferResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub application_id: Uuid,
    pub proposed_salary: Option<Decimal>,
    pub employment_type: Option<String>,
    pub letter_template_id: Option<Uuid>,
    pub status: OfferStatus,
    pub offered_at: Option<DateTime<Utc>>,
    pub accepted_at: Option<DateTime<Utc>>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for JobOffer entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct JobOfferListResponseDto {
    /// List of items
    pub items: Vec<JobOfferResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl JobOfferListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<JobOfferResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct JobOfferSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub application_id: Uuid,
    pub proposed_salary: Option<Decimal>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<JobOffer> for JobOfferResponseDto {
    fn from(entity: JobOffer) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            application_id: entity.application_id,
            proposed_salary: entity.proposed_salary,
            employment_type: entity.employment_type,
            letter_template_id: entity.letter_template_id,
            status: entity.status,
            offered_at: entity.offered_at,
            accepted_at: entity.accepted_at,
            metadata: entity.metadata,
        }
    }
}

impl From<JobOffer> for JobOfferSummaryDto {
    fn from(entity: JobOffer) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            application_id: entity.application_id,
            proposed_salary: entity.proposed_salary,
            created_at,
        }
    }
}

impl From<CreateJobOfferDto> for JobOffer {
    fn from(dto: CreateJobOfferDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            application_id: dto.application_id,
            proposed_salary: dto.proposed_salary,
            employment_type: dto.employment_type,
            letter_template_id: dto.letter_template_id,
            status: dto.status,
            offered_at: dto.offered_at,
            accepted_at: dto.accepted_at,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&JobOffer> for JobOfferResponseDto {
    fn from(entity: &JobOffer) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            application_id: entity.application_id.clone(),
            proposed_salary: entity.proposed_salary.clone(),
            employment_type: entity.employment_type.clone(),
            letter_template_id: entity.letter_template_id.clone(),
            status: entity.status.clone(),
            offered_at: entity.offered_at.clone(),
            accepted_at: entity.accepted_at.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateJobOfferDto> for JobOffer {
    fn from_create_dto(dto: CreateJobOfferDto) -> backbone_core::ServiceResult<Self> {
        Ok(JobOffer::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateJobOfferDto> for JobOffer {
    fn apply_update(mut self, dto: UpdateJobOfferDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.application_id = dto.application_id;
        self.proposed_salary = dto.proposed_salary;
        self.employment_type = dto.employment_type;
        self.letter_template_id = dto.letter_template_id;
        self.status = dto.status;
        self.offered_at = dto.offered_at;
        self.accepted_at = dto.accepted_at;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to JobOffer here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

