//! JobApplication DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::JobApplication;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new JobApplication
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateJobApplicationDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "candidate_id")]
    pub candidate_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "requisition_id")]
    pub requisition_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "stage_id")]
    pub stage_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "last_stage_id")]
    pub last_stage_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "stage_updated_at")]
    pub stage_updated_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "date_closed")]
    pub date_closed: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "refuse_reason")]
    pub refuse_reason: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "refused_at")]
    pub refused_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "applied_at")]
    pub applied_at: DateTime<Utc>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a JobApplication
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateJobApplicationDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "candidate_id")]
    pub candidate_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "requisition_id")]
    pub requisition_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "stage_id")]
    pub stage_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "last_stage_id")]
    pub last_stage_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "stage_updated_at")]
    pub stage_updated_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "date_closed")]
    pub date_closed: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "refuse_reason")]
    pub refuse_reason: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "refused_at")]
    pub refused_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "applied_at")]
    pub applied_at: DateTime<Utc>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a JobApplication
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchJobApplicationDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "candidate_id")]
    pub candidate_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "requisition_id")]
    pub requisition_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "stage_id")]
    pub stage_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "last_stage_id")]
    pub last_stage_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "stage_updated_at")]
    pub stage_updated_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "date_closed")]
    pub date_closed: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "refuse_reason")]
    pub refuse_reason: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "refused_at")]
    pub refused_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "applied_at")]
    pub applied_at: Option<DateTime<Utc>>,
}

impl PatchJobApplicationDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.candidate_id.is_some() || self.requisition_id.is_some() || self.stage_id.is_some() || self.last_stage_id.is_some() || self.stage_updated_at.is_some() || self.date_closed.is_some() || self.refuse_reason.is_some() || self.refused_at.is_some() || self.applied_at.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for JobApplication entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct JobApplicationResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub candidate_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub requisition_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub stage_id: Uuid,
    pub last_stage_id: Option<Uuid>,
    pub stage_updated_at: Option<DateTime<Utc>>,
    pub date_closed: Option<DateTime<Utc>>,
    pub refuse_reason: Option<String>,
    pub refused_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub applied_at: DateTime<Utc>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for JobApplication entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct JobApplicationListResponseDto {
    /// List of items
    pub items: Vec<JobApplicationResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl JobApplicationListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<JobApplicationResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct JobApplicationSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub candidate_id: Uuid,
    pub requisition_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<JobApplication> for JobApplicationResponseDto {
    fn from(entity: JobApplication) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            candidate_id: entity.candidate_id,
            requisition_id: entity.requisition_id,
            stage_id: entity.stage_id,
            last_stage_id: entity.last_stage_id,
            stage_updated_at: entity.stage_updated_at,
            date_closed: entity.date_closed,
            refuse_reason: entity.refuse_reason,
            refused_at: entity.refused_at,
            applied_at: entity.applied_at,
            metadata: entity.metadata,
        }
    }
}

impl From<JobApplication> for JobApplicationSummaryDto {
    fn from(entity: JobApplication) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            candidate_id: entity.candidate_id,
            requisition_id: entity.requisition_id,
            created_at,
        }
    }
}

impl From<CreateJobApplicationDto> for JobApplication {
    fn from(dto: CreateJobApplicationDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            candidate_id: dto.candidate_id,
            requisition_id: dto.requisition_id,
            stage_id: dto.stage_id,
            last_stage_id: dto.last_stage_id,
            stage_updated_at: dto.stage_updated_at,
            date_closed: dto.date_closed,
            refuse_reason: dto.refuse_reason,
            refused_at: dto.refused_at,
            applied_at: dto.applied_at,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&JobApplication> for JobApplicationResponseDto {
    fn from(entity: &JobApplication) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            candidate_id: entity.candidate_id.clone(),
            requisition_id: entity.requisition_id.clone(),
            stage_id: entity.stage_id.clone(),
            last_stage_id: entity.last_stage_id.clone(),
            stage_updated_at: entity.stage_updated_at.clone(),
            date_closed: entity.date_closed.clone(),
            refuse_reason: entity.refuse_reason.clone(),
            refused_at: entity.refused_at.clone(),
            applied_at: entity.applied_at.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateJobApplicationDto> for JobApplication {
    fn from_create_dto(dto: CreateJobApplicationDto) -> backbone_core::ServiceResult<Self> {
        Ok(JobApplication::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateJobApplicationDto> for JobApplication {
    fn apply_update(mut self, dto: UpdateJobApplicationDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.candidate_id = dto.candidate_id;
        self.requisition_id = dto.requisition_id;
        self.stage_id = dto.stage_id;
        self.last_stage_id = dto.last_stage_id;
        self.stage_updated_at = dto.stage_updated_at;
        self.date_closed = dto.date_closed;
        self.refuse_reason = dto.refuse_reason;
        self.refused_at = dto.refused_at;
        self.applied_at = dto.applied_at;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to JobApplication here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

