//! JobRequisition DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::JobRequisition;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::RequisitionStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new JobRequisition
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateJobRequisitionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "department_id")]
    pub department_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "position_id")]
    pub position_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub headcount: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "filled_headcount")]
    pub filled_headcount: i32,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "employment_type")]
    pub employment_type: Option<String>,
    pub status: RequisitionStatus,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "opened_by")]
    pub opened_by: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub budget: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deadline: Option<NaiveDate>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a JobRequisition
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateJobRequisitionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "department_id")]
    pub department_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "position_id")]
    pub position_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub headcount: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "filled_headcount")]
    pub filled_headcount: i32,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "employment_type")]
    pub employment_type: Option<String>,
    pub status: RequisitionStatus,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "opened_by")]
    pub opened_by: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub budget: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deadline: Option<NaiveDate>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a JobRequisition
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchJobRequisitionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "department_id")]
    pub department_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "position_id")]
    pub position_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub headcount: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "filled_headcount")]
    pub filled_headcount: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "employment_type")]
    pub employment_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<RequisitionStatus>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "opened_by")]
    pub opened_by: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub budget: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deadline: Option<NaiveDate>,
}

impl PatchJobRequisitionDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.department_id.is_some() || self.position_id.is_some() || self.title.is_some() || self.headcount.is_some() || self.filled_headcount.is_some() || self.employment_type.is_some() || self.status.is_some() || self.opened_by.is_some() || self.budget.is_some() || self.deadline.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for JobRequisition entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct JobRequisitionResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    pub department_id: Option<Uuid>,
    pub position_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub headcount: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub filled_headcount: i32,
    pub employment_type: Option<String>,
    pub status: RequisitionStatus,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub opened_by: Uuid,
    pub budget: Option<Decimal>,
    pub deadline: Option<NaiveDate>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for JobRequisition entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct JobRequisitionListResponseDto {
    /// List of items
    pub items: Vec<JobRequisitionResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl JobRequisitionListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<JobRequisitionResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct JobRequisitionSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub department_id: Option<Uuid>,
    pub position_id: Option<Uuid>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<JobRequisition> for JobRequisitionResponseDto {
    fn from(entity: JobRequisition) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            department_id: entity.department_id,
            position_id: entity.position_id,
            title: entity.title,
            headcount: entity.headcount,
            filled_headcount: entity.filled_headcount,
            employment_type: entity.employment_type,
            status: entity.status,
            opened_by: entity.opened_by,
            budget: entity.budget,
            deadline: entity.deadline,
            metadata: entity.metadata,
        }
    }
}

impl From<JobRequisition> for JobRequisitionSummaryDto {
    fn from(entity: JobRequisition) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            department_id: entity.department_id,
            position_id: entity.position_id,
            created_at,
        }
    }
}

impl From<CreateJobRequisitionDto> for JobRequisition {
    fn from(dto: CreateJobRequisitionDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            department_id: dto.department_id,
            position_id: dto.position_id,
            title: dto.title,
            headcount: dto.headcount,
            filled_headcount: dto.filled_headcount,
            employment_type: dto.employment_type,
            status: dto.status,
            opened_by: dto.opened_by,
            budget: dto.budget,
            deadline: dto.deadline,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&JobRequisition> for JobRequisitionResponseDto {
    fn from(entity: &JobRequisition) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            department_id: entity.department_id.clone(),
            position_id: entity.position_id.clone(),
            title: entity.title.clone(),
            headcount: entity.headcount.clone(),
            filled_headcount: entity.filled_headcount.clone(),
            employment_type: entity.employment_type.clone(),
            status: entity.status.clone(),
            opened_by: entity.opened_by.clone(),
            budget: entity.budget.clone(),
            deadline: entity.deadline.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateJobRequisitionDto> for JobRequisition {
    fn from_create_dto(dto: CreateJobRequisitionDto) -> backbone_core::ServiceResult<Self> {
        Ok(JobRequisition::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateJobRequisitionDto> for JobRequisition {
    fn apply_update(mut self, dto: UpdateJobRequisitionDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.department_id = dto.department_id;
        self.position_id = dto.position_id;
        self.title = dto.title;
        self.headcount = dto.headcount;
        self.filled_headcount = dto.filled_headcount;
        self.employment_type = dto.employment_type;
        self.status = dto.status;
        self.opened_by = dto.opened_by;
        self.budget = dto.budget;
        self.deadline = dto.deadline;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to JobRequisition here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

