//! OfferLetterTemplate DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::OfferLetterTemplate;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new OfferLetterTemplate
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateOfferLetterTemplateDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub subject: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub body: String,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a OfferLetterTemplate
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateOfferLetterTemplateDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub subject: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub body: String,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a OfferLetterTemplate
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchOfferLetterTemplateDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
}

impl PatchOfferLetterTemplateDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.name.is_some() || self.subject.is_some() || self.body.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for OfferLetterTemplate entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OfferLetterTemplateResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub subject: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub body: String,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for OfferLetterTemplate entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OfferLetterTemplateListResponseDto {
    /// List of items
    pub items: Vec<OfferLetterTemplateResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl OfferLetterTemplateListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<OfferLetterTemplateResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OfferLetterTemplateSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub name: String,
    pub subject: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<OfferLetterTemplate> for OfferLetterTemplateResponseDto {
    fn from(entity: OfferLetterTemplate) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            name: entity.name,
            subject: entity.subject,
            body: entity.body,
            metadata: entity.metadata,
        }
    }
}

impl From<OfferLetterTemplate> for OfferLetterTemplateSummaryDto {
    fn from(entity: OfferLetterTemplate) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            name: entity.name,
            subject: entity.subject,
            created_at,
        }
    }
}

impl From<CreateOfferLetterTemplateDto> for OfferLetterTemplate {
    fn from(dto: CreateOfferLetterTemplateDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            name: dto.name,
            subject: dto.subject,
            body: dto.body,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&OfferLetterTemplate> for OfferLetterTemplateResponseDto {
    fn from(entity: &OfferLetterTemplate) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            name: entity.name.clone(),
            subject: entity.subject.clone(),
            body: entity.body.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateOfferLetterTemplateDto> for OfferLetterTemplate {
    fn from_create_dto(dto: CreateOfferLetterTemplateDto) -> backbone_core::ServiceResult<Self> {
        Ok(OfferLetterTemplate::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateOfferLetterTemplateDto> for OfferLetterTemplate {
    fn apply_update(mut self, dto: UpdateOfferLetterTemplateDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.name = dto.name;
        self.subject = dto.subject;
        self.body = dto.body;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to OfferLetterTemplate here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

