//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{Specification, AndSpecification, OrSpecification, NotSpecification};

pub mod candidate_specification;
pub mod interview_specification;
pub mod job_application_specification;
pub mod job_offer_specification;
pub mod job_requisition_specification;

// <<< CUSTOM
// END CUSTOM
