//! Domain policy for JobOffer aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::JobOffer;

/// Domain policy for JobOffer — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<JobOffer>` in the `// <<< CUSTOM` zone.
pub type JobOfferDomainPolicy = PermitAllPolicy<JobOffer>;

// <<< CUSTOM
// END CUSTOM
