//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod candidate_domain_policy;
pub mod interview_domain_policy;
pub mod job_application_domain_policy;
pub mod job_offer_domain_policy;
pub mod job_requisition_domain_policy;

pub use candidate_domain_policy::CandidateDomainPolicy;
pub use interview_domain_policy::InterviewDomainPolicy;
pub use job_application_domain_policy::JobApplicationDomainPolicy;
pub use job_offer_domain_policy::JobOfferDomainPolicy;
pub use job_requisition_domain_policy::JobRequisitionDomainPolicy;

// <<< CUSTOM
// END CUSTOM
