//! Application service for Candidate entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `candidate_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateCandidateDto, UpdateCandidateDto};
use crate::domain::entity::Candidate;
use crate::infrastructure::persistence::CandidateRepository;

/// Application service for Candidate entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `candidate_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct CandidateServiceCustom {
///     inner: Arc<CandidateService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type CandidateService = GenericCrudService<
    Candidate,
    CreateCandidateDto,
    UpdateCandidateDto,
    CandidateRepository,
>;

// <<< CUSTOM
// END CUSTOM
