//! Application service for JobApplication entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `job_application_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateJobApplicationDto, UpdateJobApplicationDto};
use crate::domain::entity::JobApplication;
use crate::infrastructure::persistence::JobApplicationRepository;

/// Application service for JobApplication entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `job_application_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct JobApplicationServiceCustom {
///     inner: Arc<JobApplicationService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type JobApplicationService = GenericCrudService<
    JobApplication,
    CreateJobApplicationDto,
    UpdateJobApplicationDto,
    JobApplicationRepository,
>;

// <<< CUSTOM
// END CUSTOM
