//! Application service for JobOffer entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `job_offer_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateJobOfferDto, UpdateJobOfferDto};
use crate::domain::entity::JobOffer;
use crate::infrastructure::persistence::JobOfferRepository;

/// Application service for JobOffer entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `job_offer_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct JobOfferServiceCustom {
///     inner: Arc<JobOfferService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type JobOfferService = GenericCrudService<
    JobOffer,
    CreateJobOfferDto,
    UpdateJobOfferDto,
    JobOfferRepository,
>;

// <<< CUSTOM
// END CUSTOM
