//! Application service for JobRequisition entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `job_requisition_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateJobRequisitionDto, UpdateJobRequisitionDto};
use crate::domain::entity::JobRequisition;
use crate::infrastructure::persistence::JobRequisitionRepository;

/// Application service for JobRequisition entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `job_requisition_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct JobRequisitionServiceCustom {
///     inner: Arc<JobRequisitionService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type JobRequisitionService = GenericCrudService<
    JobRequisition,
    CreateJobRequisitionDto,
    UpdateJobRequisitionDto,
    JobRequisitionRepository,
>;

// <<< CUSTOM
// END CUSTOM
