//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod candidate_service;
pub mod interview_service;
pub mod job_application_service;
pub mod job_offer_service;
pub mod job_requisition_service;

// <<< CUSTOM
// The hire write-service (ADR-005 producer): offer→accepted + `recruitment.hired` outbox emit, in one tx.
// User-owned custom file — never regenerated.
pub mod job_offer_write_service;
// END CUSTOM

pub use candidate_service::CandidateService;
pub use interview_service::InterviewService;
pub use job_application_service::JobApplicationService;
pub use job_offer_service::JobOfferService;
pub use job_requisition_service::JobRequisitionService;
// <<< CUSTOM
pub use job_offer_write_service::{HireError, JobOfferWriteService, HIRED_EVENT_TYPE};
// END CUSTOM
