//! Application service for RequisitionSkill entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `requisition_skill_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateRequisitionSkillDto, UpdateRequisitionSkillDto};
use crate::domain::entity::RequisitionSkill;
use crate::infrastructure::persistence::RequisitionSkillRepository;

/// Application service for RequisitionSkill entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `requisition_skill_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct RequisitionSkillServiceCustom {
///     inner: Arc<RequisitionSkillService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type RequisitionSkillService = GenericCrudService<
    RequisitionSkill,
    CreateRequisitionSkillDto,
    UpdateRequisitionSkillDto,
    RequisitionSkillRepository,
>;

// <<< CUSTOM
// END CUSTOM
