-- Candidate Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the recruitment.candidates table.
-- Customize this file to add your initial data.

-- INSERT INTO recruitment.candidates (
--     id,
--     company_id,
--     first_name,
--     last_name,
--     email,
--     phone,
--     source,
--     current_employer,
--     resume_url,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO recruitment.candidates (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

