-- Interview Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the recruitment.interviews table.
-- Customize this file to add your initial data.

-- INSERT INTO recruitment.interviews (
--     id,
--     company_id,
--     application_id,
--     interviewer_id,
--     scheduled_at,
--     round,
--     interview_format,
--     rating,
--     feedback,
--     status,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO recruitment.interviews (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

