-- JobApplication Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the recruitment.job_applications table.
-- Customize this file to add your initial data.

-- INSERT INTO recruitment.job_applications (
--     id,
--     company_id,
--     candidate_id,
--     requisition_id,
--     status,
--     applied_at,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO recruitment.job_applications (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

