-- JobRequisition Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the recruitment.job_requisitions table.
-- Customize this file to add your initial data.

-- INSERT INTO recruitment.job_requisitions (
--     id,
--     company_id,
--     department_id,
--     position_id,
--     title,
--     headcount,
--     employment_type,
--     status,
--     opened_by,
--     budget,
--     deadline,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO recruitment.job_requisitions (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

