-- JobOffer Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the recruitment.job_offers table.
-- Customize this file to add your initial data.

-- INSERT INTO recruitment.job_offers (
--     id,
--     company_id,
--     application_id,
--     proposed_salary,
--     employment_type,
--     status,
--     offered_at,
--     accepted_at,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO recruitment.job_offers (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

