-- RequisitionSkill Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the recruitment.requisition_skills table.
-- Customize this file to add your initial data.

-- INSERT INTO recruitment.requisition_skills (
--     id,
--     company_id,
--     requisition_id,
--     skill_id,
--     required_proficiency,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO recruitment.requisition_skills (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

