-- Company RLS fence for recruitment module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for recruitment.candidates
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE recruitment.candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE recruitment.candidates FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS candidates_company_isolation ON recruitment.candidates;
CREATE POLICY candidates_company_isolation ON recruitment.candidates
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for recruitment.interviews
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE recruitment.interviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE recruitment.interviews FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS interviews_company_isolation ON recruitment.interviews;
CREATE POLICY interviews_company_isolation ON recruitment.interviews
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for recruitment.job_applications
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE recruitment.job_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE recruitment.job_applications FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS job_applications_company_isolation ON recruitment.job_applications;
CREATE POLICY job_applications_company_isolation ON recruitment.job_applications
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for recruitment.job_offers
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE recruitment.job_offers ENABLE ROW LEVEL SECURITY;
ALTER TABLE recruitment.job_offers FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS job_offers_company_isolation ON recruitment.job_offers;
CREATE POLICY job_offers_company_isolation ON recruitment.job_offers
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for recruitment.job_requisitions
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE recruitment.job_requisitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE recruitment.job_requisitions FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS job_requisitions_company_isolation ON recruitment.job_requisitions;
CREATE POLICY job_requisitions_company_isolation ON recruitment.job_requisitions
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

