-- Migration: Create job_offers table
-- Generated by metaphor-schema

-- Create offer_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'offer_status') THEN
        CREATE TYPE offer_status AS ENUM ('draft', 'extended', 'accepted', 'declined', 'withdrawn');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS recruitment;

CREATE TABLE IF NOT EXISTS recruitment.job_offers (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    application_id UUID NOT NULL,
    proposed_salary NUMERIC,
    employment_type TEXT,
    status offer_status NOT NULL DEFAULT 'draft',
    offered_at TIMESTAMPTZ,
    accepted_at TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_job_offers_company_id_status ON recruitment.job_offers (company_id, status);

CREATE INDEX IF NOT EXISTS idx_job_offers_application_id ON recruitment.job_offers (application_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_job_offers_metadata_gin ON recruitment.job_offers USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_job_offers_metadata_deleted_at ON recruitment.job_offers ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_job_offers_metadata_created_at ON recruitment.job_offers ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_job_offers_metadata_updated_at ON recruitment.job_offers ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION recruitment.job_offers_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS job_offers_insert_audit ON recruitment.job_offers;
CREATE TRIGGER job_offers_insert_audit BEFORE INSERT ON recruitment.job_offers
    FOR EACH ROW EXECUTE FUNCTION recruitment.job_offers_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS job_offers_update_audit ON recruitment.job_offers;
CREATE TRIGGER job_offers_update_audit BEFORE UPDATE ON recruitment.job_offers
    FOR EACH ROW EXECUTE FUNCTION recruitment.job_offers_audit_timestamp();
