-- Enum types for recruitment module
-- Generated by metaphor-schema

-- Create candidate_source enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'candidate_source') THEN
        CREATE TYPE candidate_source AS ENUM ('direct', 'referral', 'job_board', 'agency', 'walk_in');
    END IF;
END
$$;

-- Create interview_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'interview_status') THEN
        CREATE TYPE interview_status AS ENUM ('scheduled', 'completed', 'cancelled', 'no_show');
    END IF;
END
$$;

-- Create application_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'application_status') THEN
        CREATE TYPE application_status AS ENUM ('applied', 'screening', 'interview', 'offer', 'hired', 'rejected');
    END IF;
END
$$;

-- Create offer_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'offer_status') THEN
        CREATE TYPE offer_status AS ENUM ('draft', 'extended', 'accepted', 'declined', 'withdrawn');
    END IF;
END
$$;

-- Create requisition_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'requisition_status') THEN
        CREATE TYPE requisition_status AS ENUM ('draft', 'open', 'on_hold', 'closed', 'cancelled');
    END IF;
END
$$;

