-- Migration: Create requisition_skills table
-- Generated by metaphor-schema

-- Create proficiency_level enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'proficiency_level') THEN
        CREATE TYPE proficiency_level AS ENUM ('novice', 'beginner', 'intermediate', 'advanced', 'expert');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS recruitment;

CREATE TABLE IF NOT EXISTS recruitment.requisition_skills (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    requisition_id UUID NOT NULL,
    skill_id UUID NOT NULL,
    required_proficiency proficiency_level NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_requisition_skills_company_id_requisition_id_skill_id ON recruitment.requisition_skills (company_id, requisition_id, skill_id);

CREATE INDEX IF NOT EXISTS idx_requisition_skills_skill_id ON recruitment.requisition_skills (skill_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_requisition_skills_metadata_gin ON recruitment.requisition_skills USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_requisition_skills_metadata_deleted_at ON recruitment.requisition_skills ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_requisition_skills_metadata_created_at ON recruitment.requisition_skills ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_requisition_skills_metadata_updated_at ON recruitment.requisition_skills ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION recruitment.requisition_skills_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS requisition_skills_insert_audit ON recruitment.requisition_skills;
CREATE TRIGGER requisition_skills_insert_audit BEFORE INSERT ON recruitment.requisition_skills
    FOR EACH ROW EXECUTE FUNCTION recruitment.requisition_skills_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS requisition_skills_update_audit ON recruitment.requisition_skills;
CREATE TRIGGER requisition_skills_update_audit BEFORE UPDATE ON recruitment.requisition_skills
    FOR EACH ROW EXECUTE FUNCTION recruitment.requisition_skills_audit_timestamp();
