-- Migration: Create job_requisitions table
-- Generated by metaphor-schema

-- Create requisition_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'requisition_status') THEN
        CREATE TYPE requisition_status AS ENUM ('draft', 'open', 'on_hold', 'closed', 'cancelled');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS recruitment;

CREATE TABLE IF NOT EXISTS recruitment.job_requisitions (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    department_id UUID,
    position_id UUID,
    title TEXT NOT NULL,
    headcount INTEGER NOT NULL CHECK (headcount >= 0),
    employment_type TEXT,
    status requisition_status NOT NULL DEFAULT 'draft',
    opened_by UUID NOT NULL,
    budget NUMERIC,
    deadline DATE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_job_requisitions_company_id_status ON recruitment.job_requisitions (company_id, status);

CREATE INDEX IF NOT EXISTS idx_job_requisitions_department_id ON recruitment.job_requisitions (department_id);

CREATE INDEX IF NOT EXISTS idx_job_requisitions_opened_by ON recruitment.job_requisitions (opened_by);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_job_requisitions_metadata_gin ON recruitment.job_requisitions USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_job_requisitions_metadata_deleted_at ON recruitment.job_requisitions ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_job_requisitions_metadata_created_at ON recruitment.job_requisitions ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_job_requisitions_metadata_updated_at ON recruitment.job_requisitions ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION recruitment.job_requisitions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS job_requisitions_insert_audit ON recruitment.job_requisitions;
CREATE TRIGGER job_requisitions_insert_audit BEFORE INSERT ON recruitment.job_requisitions
    FOR EACH ROW EXECUTE FUNCTION recruitment.job_requisitions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS job_requisitions_update_audit ON recruitment.job_requisitions;
CREATE TRIGGER job_requisitions_update_audit BEFORE UPDATE ON recruitment.job_requisitions
    FOR EACH ROW EXECUTE FUNCTION recruitment.job_requisitions_audit_timestamp();
