-- Migration: Create interviews table
-- Generated by metaphor-schema

-- Create interview_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'interview_status') THEN
        CREATE TYPE interview_status AS ENUM ('scheduled', 'completed', 'cancelled', 'no_show');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS recruitment;

CREATE TABLE IF NOT EXISTS recruitment.interviews (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    application_id UUID NOT NULL,
    interviewer_id UUID NOT NULL,
    scheduled_at TIMESTAMPTZ NOT NULL,
    round INTEGER CHECK (round >= 0),
    interview_format TEXT,
    rating INTEGER CHECK (rating >= 0),
    feedback TEXT,
    status interview_status NOT NULL DEFAULT 'scheduled',
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_interviews_company_id_status ON recruitment.interviews (company_id, status);

CREATE INDEX IF NOT EXISTS idx_interviews_application_id ON recruitment.interviews (application_id);

CREATE INDEX IF NOT EXISTS idx_interviews_interviewer_id ON recruitment.interviews (interviewer_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_interviews_metadata_gin ON recruitment.interviews USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_interviews_metadata_deleted_at ON recruitment.interviews ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_interviews_metadata_created_at ON recruitment.interviews ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_interviews_metadata_updated_at ON recruitment.interviews ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION recruitment.interviews_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS interviews_insert_audit ON recruitment.interviews;
CREATE TRIGGER interviews_insert_audit BEFORE INSERT ON recruitment.interviews
    FOR EACH ROW EXECUTE FUNCTION recruitment.interviews_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS interviews_update_audit ON recruitment.interviews;
CREATE TRIGGER interviews_update_audit BEFORE UPDATE ON recruitment.interviews
    FOR EACH ROW EXECUTE FUNCTION recruitment.interviews_audit_timestamp();
