-- Migration: Create candidates table
-- Generated by metaphor-schema

-- Create candidate_source enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'candidate_source') THEN
        CREATE TYPE candidate_source AS ENUM ('direct', 'referral', 'job_board', 'agency', 'walk_in');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS recruitment;

CREATE TABLE IF NOT EXISTS recruitment.candidates (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT,
    email TEXT,
    phone TEXT,
    source candidate_source,
    current_employer TEXT,
    resume_url TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_candidates_company_id ON recruitment.candidates (company_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_candidates_company_id_email ON recruitment.candidates (company_id, email) WHERE (metadata->>'deleted_at') IS NULL;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_candidates_metadata_gin ON recruitment.candidates USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_candidates_metadata_deleted_at ON recruitment.candidates ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_candidates_metadata_created_at ON recruitment.candidates ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_candidates_metadata_updated_at ON recruitment.candidates ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION recruitment.candidates_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS candidates_insert_audit ON recruitment.candidates;
CREATE TRIGGER candidates_insert_audit BEFORE INSERT ON recruitment.candidates
    FOR EACH ROW EXECUTE FUNCTION recruitment.candidates_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS candidates_update_audit ON recruitment.candidates;
CREATE TRIGGER candidates_update_audit BEFORE UPDATE ON recruitment.candidates
    FOR EACH ROW EXECUTE FUNCTION recruitment.candidates_audit_timestamp();
