-- Migration: Create recruitment_stages table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS recruitment;

CREATE TABLE IF NOT EXISTS recruitment.recruitment_stages (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    name TEXT NOT NULL,
    sequence INTEGER NOT NULL DEFAULT 10 CHECK (sequence >= 0),
    is_hired BOOLEAN NOT NULL DEFAULT FALSE,
    folded BOOLEAN NOT NULL DEFAULT FALSE,
    description TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_recruitment_stages_company_id_name ON recruitment.recruitment_stages (company_id, name);

CREATE INDEX IF NOT EXISTS idx_recruitment_stages_company_id_sequence ON recruitment.recruitment_stages (company_id, sequence);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_recruitment_stages_metadata_gin ON recruitment.recruitment_stages USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_recruitment_stages_metadata_deleted_at ON recruitment.recruitment_stages ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_recruitment_stages_metadata_created_at ON recruitment.recruitment_stages ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_recruitment_stages_metadata_updated_at ON recruitment.recruitment_stages ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION recruitment.recruitment_stages_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS recruitment_stages_insert_audit ON recruitment.recruitment_stages;
CREATE TRIGGER recruitment_stages_insert_audit BEFORE INSERT ON recruitment.recruitment_stages
    FOR EACH ROW EXECUTE FUNCTION recruitment.recruitment_stages_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS recruitment_stages_update_audit ON recruitment.recruitment_stages;
CREATE TRIGGER recruitment_stages_update_audit BEFORE UPDATE ON recruitment.recruitment_stages
    FOR EACH ROW EXECUTE FUNCTION recruitment.recruitment_stages_audit_timestamp();
