-- Migration: Create offer_letter_templates table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS recruitment;

CREATE TABLE IF NOT EXISTS recruitment.offer_letter_templates (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    name TEXT NOT NULL,
    subject TEXT NOT NULL,
    body TEXT NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_offer_letter_templates_company_id_name ON recruitment.offer_letter_templates (company_id, name);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_offer_letter_templates_metadata_gin ON recruitment.offer_letter_templates USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_offer_letter_templates_metadata_deleted_at ON recruitment.offer_letter_templates ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_offer_letter_templates_metadata_created_at ON recruitment.offer_letter_templates ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_offer_letter_templates_metadata_updated_at ON recruitment.offer_letter_templates ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION recruitment.offer_letter_templates_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS offer_letter_templates_insert_audit ON recruitment.offer_letter_templates;
CREATE TRIGGER offer_letter_templates_insert_audit BEFORE INSERT ON recruitment.offer_letter_templates
    FOR EACH ROW EXECUTE FUNCTION recruitment.offer_letter_templates_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS offer_letter_templates_update_audit ON recruitment.offer_letter_templates;
CREATE TRIGGER offer_letter_templates_update_audit BEFORE UPDATE ON recruitment.offer_letter_templates
    FOR EACH ROW EXECUTE FUNCTION recruitment.offer_letter_templates_audit_timestamp();
