-- Audit Triggers Migration for recruitment module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: Candidate (recruitment.candidates)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION recruitment.candidates_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS candidates_insert_audit ON recruitment.candidates;
CREATE TRIGGER candidates_insert_audit BEFORE INSERT ON recruitment.candidates
    FOR EACH ROW EXECUTE FUNCTION recruitment.candidates_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS candidates_update_audit ON recruitment.candidates;
CREATE TRIGGER candidates_update_audit BEFORE UPDATE ON recruitment.candidates
    FOR EACH ROW EXECUTE FUNCTION recruitment.candidates_audit_timestamp();

-- ==============================================================================
-- Table: Interview (recruitment.interviews)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION recruitment.interviews_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS interviews_insert_audit ON recruitment.interviews;
CREATE TRIGGER interviews_insert_audit BEFORE INSERT ON recruitment.interviews
    FOR EACH ROW EXECUTE FUNCTION recruitment.interviews_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS interviews_update_audit ON recruitment.interviews;
CREATE TRIGGER interviews_update_audit BEFORE UPDATE ON recruitment.interviews
    FOR EACH ROW EXECUTE FUNCTION recruitment.interviews_audit_timestamp();

-- ==============================================================================
-- Table: JobApplication (recruitment.job_applications)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION recruitment.job_applications_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS job_applications_insert_audit ON recruitment.job_applications;
CREATE TRIGGER job_applications_insert_audit BEFORE INSERT ON recruitment.job_applications
    FOR EACH ROW EXECUTE FUNCTION recruitment.job_applications_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS job_applications_update_audit ON recruitment.job_applications;
CREATE TRIGGER job_applications_update_audit BEFORE UPDATE ON recruitment.job_applications
    FOR EACH ROW EXECUTE FUNCTION recruitment.job_applications_audit_timestamp();

-- ==============================================================================
-- Table: JobOffer (recruitment.job_offers)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION recruitment.job_offers_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS job_offers_insert_audit ON recruitment.job_offers;
CREATE TRIGGER job_offers_insert_audit BEFORE INSERT ON recruitment.job_offers
    FOR EACH ROW EXECUTE FUNCTION recruitment.job_offers_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS job_offers_update_audit ON recruitment.job_offers;
CREATE TRIGGER job_offers_update_audit BEFORE UPDATE ON recruitment.job_offers
    FOR EACH ROW EXECUTE FUNCTION recruitment.job_offers_audit_timestamp();

-- ==============================================================================
-- Table: JobRequisition (recruitment.job_requisitions)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION recruitment.job_requisitions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS job_requisitions_insert_audit ON recruitment.job_requisitions;
CREATE TRIGGER job_requisitions_insert_audit BEFORE INSERT ON recruitment.job_requisitions
    FOR EACH ROW EXECUTE FUNCTION recruitment.job_requisitions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS job_requisitions_update_audit ON recruitment.job_requisitions;
CREATE TRIGGER job_requisitions_update_audit BEFORE UPDATE ON recruitment.job_requisitions
    FOR EACH ROW EXECUTE FUNCTION recruitment.job_requisitions_audit_timestamp();

