-- Migration: Create job_applications table
-- Generated by metaphor-schema

-- Create application_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'application_status') THEN
        CREATE TYPE application_status AS ENUM ('applied', 'screening', 'interview', 'offer', 'hired', 'rejected');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS recruitment;

CREATE TABLE IF NOT EXISTS recruitment.job_applications (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    candidate_id UUID NOT NULL,
    requisition_id UUID NOT NULL,
    status application_status NOT NULL DEFAULT 'applied',
    applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_job_applications_company_id_status ON recruitment.job_applications (company_id, status);

CREATE INDEX IF NOT EXISTS idx_job_applications_candidate_id ON recruitment.job_applications (candidate_id);

CREATE INDEX IF NOT EXISTS idx_job_applications_requisition_id ON recruitment.job_applications (requisition_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_job_applications_metadata_gin ON recruitment.job_applications USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_job_applications_metadata_deleted_at ON recruitment.job_applications ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_job_applications_metadata_created_at ON recruitment.job_applications ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_job_applications_metadata_updated_at ON recruitment.job_applications ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION recruitment.job_applications_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS job_applications_insert_audit ON recruitment.job_applications;
CREATE TRIGGER job_applications_insert_audit BEFORE INSERT ON recruitment.job_applications
    FOR EACH ROW EXECUTE FUNCTION recruitment.job_applications_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS job_applications_update_audit ON recruitment.job_applications;
CREATE TRIGGER job_applications_update_audit BEFORE UPDATE ON recruitment.job_applications
    FOR EACH ROW EXECUTE FUNCTION recruitment.job_applications_audit_timestamp();
