//! Event handler trait for Candidate events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::CandidateEvent;

/// Event handler for Candidate events.
/// Implement this trait to react to Candidate lifecycle events.
pub trait CandidateEventHandler: EventHandler<CandidateEvent> {}
