//! Domain events for Candidate entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Candidate;

/// Domain events for Candidate — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Candidate>)` variant.
pub type CandidateEvent = CrudEvent<Candidate>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Candidate events.
pub type CandidateEventPublisher = Arc<dyn CrudEventPublisher<Candidate> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopCandidateEventPublisher = NoOpCrudEventPublisher<Candidate>;
