//! Event handler trait for Interview events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::InterviewEvent;

/// Event handler for Interview events.
/// Implement this trait to react to Interview lifecycle events.
pub trait InterviewEventHandler: EventHandler<InterviewEvent> {}
