//! Domain events for Interview entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Interview;

/// Domain events for Interview — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Interview>)` variant.
pub type InterviewEvent = CrudEvent<Interview>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Interview events.
pub type InterviewEventPublisher = Arc<dyn CrudEventPublisher<Interview> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopInterviewEventPublisher = NoOpCrudEventPublisher<Interview>;
