//! Domain events for JobOffer entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::JobOffer;

/// Domain events for JobOffer — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<JobOffer>)` variant.
pub type JobOfferEvent = CrudEvent<JobOffer>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for JobOffer events.
pub type JobOfferEventPublisher = Arc<dyn CrudEventPublisher<JobOffer> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopJobOfferEventPublisher = NoOpCrudEventPublisher<JobOffer>;
