//! Event handler trait for JobRequisition events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::JobRequisitionEvent;

/// Event handler for JobRequisition events.
/// Implement this trait to react to JobRequisition lifecycle events.
pub trait JobRequisitionEventHandler: EventHandler<JobRequisitionEvent> {}
