//! Domain events for JobRequisition entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::JobRequisition;

/// Domain events for JobRequisition — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<JobRequisition>)` variant.
pub type JobRequisitionEvent = CrudEvent<JobRequisition>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for JobRequisition events.
pub type JobRequisitionEventPublisher = Arc<dyn CrudEventPublisher<JobRequisition> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopJobRequisitionEventPublisher = NoOpCrudEventPublisher<JobRequisition>;
