//! Event handler trait for JobApplication events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::JobApplicationEvent;

/// Event handler for JobApplication events.
/// Implement this trait to react to JobApplication lifecycle events.
pub trait JobApplicationEventHandler: EventHandler<JobApplicationEvent> {}
