//! Event handler trait for JobOffer events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::JobOfferEvent;

/// Event handler for JobOffer events.
/// Implement this trait to react to JobOffer lifecycle events.
pub trait JobOfferEventHandler: EventHandler<JobOfferEvent> {}
