//! Domain events for JobApplication entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::JobApplication;

/// Domain events for JobApplication — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<JobApplication>)` variant.
pub type JobApplicationEvent = CrudEvent<JobApplication>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for JobApplication events.
pub type JobApplicationEventPublisher = Arc<dyn CrudEventPublisher<JobApplication> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopJobApplicationEventPublisher = NoOpCrudEventPublisher<JobApplication>;
