//! Domain events for OfferLetterTemplate entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::OfferLetterTemplate;

/// Domain events for OfferLetterTemplate — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<OfferLetterTemplate>)` variant.
pub type OfferLetterTemplateEvent = CrudEvent<OfferLetterTemplate>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for OfferLetterTemplate events.
pub type OfferLetterTemplateEventPublisher = Arc<dyn CrudEventPublisher<OfferLetterTemplate> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopOfferLetterTemplateEventPublisher = NoOpCrudEventPublisher<OfferLetterTemplate>;
