//! Event handler trait for OfferLetterTemplate events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::OfferLetterTemplateEvent;

/// Event handler for OfferLetterTemplate events.
/// Implement this trait to react to OfferLetterTemplate lifecycle events.
pub trait OfferLetterTemplateEventHandler: EventHandler<OfferLetterTemplateEvent> {}
