//! Event handler trait for RecruitmentStage events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::RecruitmentStageEvent;

/// Event handler for RecruitmentStage events.
/// Implement this trait to react to RecruitmentStage lifecycle events.
pub trait RecruitmentStageEventHandler: EventHandler<RecruitmentStageEvent> {}
