//! Domain events for RecruitmentStage entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::RecruitmentStage;

/// Domain events for RecruitmentStage — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<RecruitmentStage>)` variant.
pub type RecruitmentStageEvent = CrudEvent<RecruitmentStage>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for RecruitmentStage events.
pub type RecruitmentStageEventPublisher = Arc<dyn CrudEventPublisher<RecruitmentStage> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopRecruitmentStageEventPublisher = NoOpCrudEventPublisher<RecruitmentStage>;
