//! Event handler trait for RequisitionSkill events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::RequisitionSkillEvent;

/// Event handler for RequisitionSkill events.
/// Implement this trait to react to RequisitionSkill lifecycle events.
pub trait RequisitionSkillEventHandler: EventHandler<RequisitionSkillEvent> {}
