//! Domain events for RequisitionSkill entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::RequisitionSkill;

/// Domain events for RequisitionSkill — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<RequisitionSkill>)` variant.
pub type RequisitionSkillEvent = CrudEvent<RequisitionSkill>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for RequisitionSkill events.
pub type RequisitionSkillEventPublisher = Arc<dyn CrudEventPublisher<RequisitionSkill> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopRequisitionSkillEventPublisher = NoOpCrudEventPublisher<RequisitionSkill>;
