//! Candidate seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial Candidate data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// CANDIDATE SEEDER
// ============================================================================

/// Seeder for candidate
pub struct SeedCandidateSeeder;

impl SeedCandidateSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedCandidateSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedCandidateSeeder {
    fn name(&self) -> &'static str {
        "SeedCandidateSeeder"
    }

    fn order(&self) -> i32 {
        1
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if recruitment.candidates table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM recruitment.candidates")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/candidate_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM recruitment.candidates")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

