//! Interview seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial Interview data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// INTERVIEW SEEDER
// ============================================================================

/// Seeder for interview
pub struct SeedInterviewSeeder;

impl SeedInterviewSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedInterviewSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedInterviewSeeder {
    fn name(&self) -> &'static str {
        "SeedInterviewSeeder"
    }

    fn order(&self) -> i32 {
        2
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if recruitment.interviews table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM recruitment.interviews")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/interview_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM recruitment.interviews")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

