//! JobRequisition seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial JobRequisition data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// JOBREQUISITION SEEDER
// ============================================================================

/// Seeder for job_requisition
pub struct SeedJobRequisitionSeeder;

impl SeedJobRequisitionSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedJobRequisitionSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedJobRequisitionSeeder {
    fn name(&self) -> &'static str {
        "SeedJobRequisitionSeeder"
    }

    fn order(&self) -> i32 {
        5
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if recruitment.job_requisitions table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM recruitment.job_requisitions")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/job_requisition_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM recruitment.job_requisitions")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

