//! OfferLetterTemplate seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial OfferLetterTemplate data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// OFFERLETTERTEMPLATE SEEDER
// ============================================================================

/// Seeder for offer_letter_template
pub struct SeedOfferLetterTemplateSeeder;

impl SeedOfferLetterTemplateSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedOfferLetterTemplateSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedOfferLetterTemplateSeeder {
    fn name(&self) -> &'static str {
        "SeedOfferLetterTemplateSeeder"
    }

    fn order(&self) -> i32 {
        6
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if recruitment.offer_letter_templates table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM recruitment.offer_letter_templates")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/offer_letter_template_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM recruitment.offer_letter_templates")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

