//! RecruitmentStage seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial RecruitmentStage data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// RECRUITMENTSTAGE SEEDER
// ============================================================================

/// Seeder for recruitment_stage
pub struct SeedRecruitmentStageSeeder;

impl SeedRecruitmentStageSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedRecruitmentStageSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedRecruitmentStageSeeder {
    fn name(&self) -> &'static str {
        "SeedRecruitmentStageSeeder"
    }

    fn order(&self) -> i32 {
        7
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if recruitment.recruitment_stages table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM recruitment.recruitment_stages")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/recruitment_stage_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM recruitment.recruitment_stages")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

