//! RequisitionSkill seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial RequisitionSkill data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// REQUISITIONSKILL SEEDER
// ============================================================================

/// Seeder for requisition_skill
pub struct SeedRequisitionSkillSeeder;

impl SeedRequisitionSkillSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedRequisitionSkillSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedRequisitionSkillSeeder {
    fn name(&self) -> &'static str {
        "SeedRequisitionSkillSeeder"
    }

    fn order(&self) -> i32 {
        8
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if recruitment.requisition_skills table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM recruitment.requisition_skills")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/requisition_skill_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM recruitment.requisition_skills")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

