//! Repository trait for Candidate aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Candidate aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Candidate, CandidateSource};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CandidatePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl CandidatePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct CandidatePaginatedResult {
    pub data: Vec<Candidate>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CandidateFilter {
    pub company_id: Option<Uuid>,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    pub email: Option<String>,
    pub phone: Option<String>,
    pub source: Option<CandidateSource>,
    pub current_employer: Option<String>,
    pub resume_url: Option<String>,
}

impl CandidateFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.first_name.is_some() || self.last_name.is_some() || self.email.is_some() || self.phone.is_some() || self.source.is_some() || self.current_employer.is_some() || self.resume_url.is_some()
    }
}

/// Repository trait for Candidate aggregate
///
/// This trait defines the persistence contract for Candidate entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait CandidateRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new candidate entity
    async fn save(&self, entity: &Candidate) -> Result<Candidate>;

    /// Find candidate by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Candidate>>;

    /// Find all candidate entities
    async fn find_all(&self) -> Result<Vec<Candidate>>;

    /// Update candidate by ID
    async fn update(&self, id: &str, entity: &Candidate) -> Result<Option<Candidate>>;

    /// Delete candidate by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List candidate with pagination
    async fn list(&self, params: CandidatePaginationParams) -> Result<CandidatePaginatedResult>;

    /// List candidate with pagination and filters
    async fn list_with_filters(&self, params: CandidatePaginationParams, filters: CandidateFilter) -> Result<CandidatePaginatedResult>;

    /// Count all candidate entities
    async fn count(&self) -> Result<u64>;

    /// Count candidate entities matching filters
    async fn count_with_filters(&self, filters: CandidateFilter) -> Result<u64>;

    /// Check if candidate exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete candidate by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted candidate by ID
    async fn restore(&self, id: &str) -> Result<Option<Candidate>>;

    /// List soft-deleted candidate entities
    async fn list_deleted(&self, params: CandidatePaginationParams) -> Result<CandidatePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save candidate entities
    async fn bulk_save(&self, entities: &[Candidate]) -> Result<Vec<Candidate>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
