//! Repository trait for Interview aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Interview aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Interview, InterviewStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct InterviewPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl InterviewPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct InterviewPaginatedResult {
    pub data: Vec<Interview>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct InterviewFilter {
    pub company_id: Option<Uuid>,
    pub application_id: Option<Uuid>,
    pub interviewer_id: Option<Uuid>,
    pub interview_format: Option<String>,
    pub feedback: Option<String>,
    pub status: Option<InterviewStatus>,
}

impl InterviewFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.application_id.is_some() || self.interviewer_id.is_some() || self.interview_format.is_some() || self.feedback.is_some() || self.status.is_some()
    }
}

/// Repository trait for Interview aggregate
///
/// This trait defines the persistence contract for Interview entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait InterviewRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new interview entity
    async fn save(&self, entity: &Interview) -> Result<Interview>;

    /// Find interview by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Interview>>;

    /// Find all interview entities
    async fn find_all(&self) -> Result<Vec<Interview>>;

    /// Update interview by ID
    async fn update(&self, id: &str, entity: &Interview) -> Result<Option<Interview>>;

    /// Delete interview by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List interview with pagination
    async fn list(&self, params: InterviewPaginationParams) -> Result<InterviewPaginatedResult>;

    /// List interview with pagination and filters
    async fn list_with_filters(&self, params: InterviewPaginationParams, filters: InterviewFilter) -> Result<InterviewPaginatedResult>;

    /// Count all interview entities
    async fn count(&self) -> Result<u64>;

    /// Count interview entities matching filters
    async fn count_with_filters(&self, filters: InterviewFilter) -> Result<u64>;

    /// Check if interview exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete interview by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted interview by ID
    async fn restore(&self, id: &str) -> Result<Option<Interview>>;

    /// List soft-deleted interview entities
    async fn list_deleted(&self, params: InterviewPaginationParams) -> Result<InterviewPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save interview entities
    async fn bulk_save(&self, entities: &[Interview]) -> Result<Vec<Interview>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
