//! Repository trait for JobOffer aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the JobOffer aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{JobOffer, OfferStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct JobOfferPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl JobOfferPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct JobOfferPaginatedResult {
    pub data: Vec<JobOffer>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct JobOfferFilter {
    pub company_id: Option<Uuid>,
    pub application_id: Option<Uuid>,
    pub employment_type: Option<String>,
    pub letter_template_id: Option<Uuid>,
    pub status: Option<OfferStatus>,
}

impl JobOfferFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.application_id.is_some() || self.employment_type.is_some() || self.letter_template_id.is_some() || self.status.is_some()
    }
}

/// Repository trait for JobOffer aggregate
///
/// This trait defines the persistence contract for JobOffer entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait JobOfferRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new job_offer entity
    async fn save(&self, entity: &JobOffer) -> Result<JobOffer>;

    /// Find job_offer by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<JobOffer>>;

    /// Find all job_offer entities
    async fn find_all(&self) -> Result<Vec<JobOffer>>;

    /// Update job_offer by ID
    async fn update(&self, id: &str, entity: &JobOffer) -> Result<Option<JobOffer>>;

    /// Delete job_offer by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List job_offer with pagination
    async fn list(&self, params: JobOfferPaginationParams) -> Result<JobOfferPaginatedResult>;

    /// List job_offer with pagination and filters
    async fn list_with_filters(&self, params: JobOfferPaginationParams, filters: JobOfferFilter) -> Result<JobOfferPaginatedResult>;

    /// Count all job_offer entities
    async fn count(&self) -> Result<u64>;

    /// Count job_offer entities matching filters
    async fn count_with_filters(&self, filters: JobOfferFilter) -> Result<u64>;

    /// Check if job_offer exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete job_offer by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted job_offer by ID
    async fn restore(&self, id: &str) -> Result<Option<JobOffer>>;

    /// List soft-deleted job_offer entities
    async fn list_deleted(&self, params: JobOfferPaginationParams) -> Result<JobOfferPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save job_offer entities
    async fn bulk_save(&self, entities: &[JobOffer]) -> Result<Vec<JobOffer>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
