//! Repository trait for JobApplication aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the JobApplication aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::JobApplication;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct JobApplicationPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl JobApplicationPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct JobApplicationPaginatedResult {
    pub data: Vec<JobApplication>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct JobApplicationFilter {
    pub company_id: Option<Uuid>,
    pub candidate_id: Option<Uuid>,
    pub requisition_id: Option<Uuid>,
    pub stage_id: Option<Uuid>,
    pub last_stage_id: Option<Uuid>,
    pub refuse_reason: Option<String>,
}

impl JobApplicationFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.candidate_id.is_some() || self.requisition_id.is_some() || self.stage_id.is_some() || self.last_stage_id.is_some() || self.refuse_reason.is_some()
    }
}

/// Repository trait for JobApplication aggregate
///
/// This trait defines the persistence contract for JobApplication entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait JobApplicationRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new job_application entity
    async fn save(&self, entity: &JobApplication) -> Result<JobApplication>;

    /// Find job_application by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<JobApplication>>;

    /// Find all job_application entities
    async fn find_all(&self) -> Result<Vec<JobApplication>>;

    /// Update job_application by ID
    async fn update(&self, id: &str, entity: &JobApplication) -> Result<Option<JobApplication>>;

    /// Delete job_application by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List job_application with pagination
    async fn list(&self, params: JobApplicationPaginationParams) -> Result<JobApplicationPaginatedResult>;

    /// List job_application with pagination and filters
    async fn list_with_filters(&self, params: JobApplicationPaginationParams, filters: JobApplicationFilter) -> Result<JobApplicationPaginatedResult>;

    /// Count all job_application entities
    async fn count(&self) -> Result<u64>;

    /// Count job_application entities matching filters
    async fn count_with_filters(&self, filters: JobApplicationFilter) -> Result<u64>;

    /// Check if job_application exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete job_application by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted job_application by ID
    async fn restore(&self, id: &str) -> Result<Option<JobApplication>>;

    /// List soft-deleted job_application entities
    async fn list_deleted(&self, params: JobApplicationPaginationParams) -> Result<JobApplicationPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save job_application entities
    async fn bulk_save(&self, entities: &[JobApplication]) -> Result<Vec<JobApplication>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
