//! Repository trait for JobRequisition aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the JobRequisition aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{JobRequisition, RequisitionStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct JobRequisitionPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl JobRequisitionPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct JobRequisitionPaginatedResult {
    pub data: Vec<JobRequisition>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct JobRequisitionFilter {
    pub company_id: Option<Uuid>,
    pub department_id: Option<Uuid>,
    pub position_id: Option<Uuid>,
    pub title: Option<String>,
    pub employment_type: Option<String>,
    pub status: Option<RequisitionStatus>,
    pub opened_by: Option<Uuid>,
}

impl JobRequisitionFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.department_id.is_some() || self.position_id.is_some() || self.title.is_some() || self.employment_type.is_some() || self.status.is_some() || self.opened_by.is_some()
    }
}

/// Repository trait for JobRequisition aggregate
///
/// This trait defines the persistence contract for JobRequisition entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait JobRequisitionRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new job_requisition entity
    async fn save(&self, entity: &JobRequisition) -> Result<JobRequisition>;

    /// Find job_requisition by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<JobRequisition>>;

    /// Find all job_requisition entities
    async fn find_all(&self) -> Result<Vec<JobRequisition>>;

    /// Update job_requisition by ID
    async fn update(&self, id: &str, entity: &JobRequisition) -> Result<Option<JobRequisition>>;

    /// Delete job_requisition by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List job_requisition with pagination
    async fn list(&self, params: JobRequisitionPaginationParams) -> Result<JobRequisitionPaginatedResult>;

    /// List job_requisition with pagination and filters
    async fn list_with_filters(&self, params: JobRequisitionPaginationParams, filters: JobRequisitionFilter) -> Result<JobRequisitionPaginatedResult>;

    /// Count all job_requisition entities
    async fn count(&self) -> Result<u64>;

    /// Count job_requisition entities matching filters
    async fn count_with_filters(&self, filters: JobRequisitionFilter) -> Result<u64>;

    /// Check if job_requisition exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete job_requisition by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted job_requisition by ID
    async fn restore(&self, id: &str) -> Result<Option<JobRequisition>>;

    /// List soft-deleted job_requisition entities
    async fn list_deleted(&self, params: JobRequisitionPaginationParams) -> Result<JobRequisitionPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save job_requisition entities
    async fn bulk_save(&self, entities: &[JobRequisition]) -> Result<Vec<JobRequisition>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
