//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod candidate_repository;
pub mod interview_repository;
pub mod job_application_repository;
pub mod job_offer_repository;
pub mod job_requisition_repository;

// Re-exports
pub use candidate_repository::{
    CandidateRepository,
    CandidatePaginationParams,
    CandidatePaginatedResult,
    CandidateFilter,
};
pub use interview_repository::{
    InterviewRepository,
    InterviewPaginationParams,
    InterviewPaginatedResult,
    InterviewFilter,
};
pub use job_application_repository::{
    JobApplicationRepository,
    JobApplicationPaginationParams,
    JobApplicationPaginatedResult,
    JobApplicationFilter,
};
pub use job_offer_repository::{
    JobOfferRepository,
    JobOfferPaginationParams,
    JobOfferPaginatedResult,
    JobOfferFilter,
};
pub use job_requisition_repository::{
    JobRequisitionRepository,
    JobRequisitionPaginationParams,
    JobRequisitionPaginatedResult,
    JobRequisitionFilter,
};
