//! Repository trait for OfferLetterTemplate aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the OfferLetterTemplate aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::OfferLetterTemplate;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct OfferLetterTemplatePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl OfferLetterTemplatePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct OfferLetterTemplatePaginatedResult {
    pub data: Vec<OfferLetterTemplate>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct OfferLetterTemplateFilter {
    pub company_id: Option<Uuid>,
    pub name: Option<String>,
    pub subject: Option<String>,
    pub body: Option<String>,
}

impl OfferLetterTemplateFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.name.is_some() || self.subject.is_some() || self.body.is_some()
    }
}

/// Repository trait for OfferLetterTemplate aggregate
///
/// This trait defines the persistence contract for OfferLetterTemplate entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait OfferLetterTemplateRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new offer_letter_template entity
    async fn save(&self, entity: &OfferLetterTemplate) -> Result<OfferLetterTemplate>;

    /// Find offer_letter_template by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<OfferLetterTemplate>>;

    /// Find all offer_letter_template entities
    async fn find_all(&self) -> Result<Vec<OfferLetterTemplate>>;

    /// Update offer_letter_template by ID
    async fn update(&self, id: &str, entity: &OfferLetterTemplate) -> Result<Option<OfferLetterTemplate>>;

    /// Delete offer_letter_template by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List offer_letter_template with pagination
    async fn list(&self, params: OfferLetterTemplatePaginationParams) -> Result<OfferLetterTemplatePaginatedResult>;

    /// List offer_letter_template with pagination and filters
    async fn list_with_filters(&self, params: OfferLetterTemplatePaginationParams, filters: OfferLetterTemplateFilter) -> Result<OfferLetterTemplatePaginatedResult>;

    /// Count all offer_letter_template entities
    async fn count(&self) -> Result<u64>;

    /// Count offer_letter_template entities matching filters
    async fn count_with_filters(&self, filters: OfferLetterTemplateFilter) -> Result<u64>;

    /// Check if offer_letter_template exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete offer_letter_template by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted offer_letter_template by ID
    async fn restore(&self, id: &str) -> Result<Option<OfferLetterTemplate>>;

    /// List soft-deleted offer_letter_template entities
    async fn list_deleted(&self, params: OfferLetterTemplatePaginationParams) -> Result<OfferLetterTemplatePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save offer_letter_template entities
    async fn bulk_save(&self, entities: &[OfferLetterTemplate]) -> Result<Vec<OfferLetterTemplate>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
