//! Repository trait for RecruitmentStage aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the RecruitmentStage aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::RecruitmentStage;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct RecruitmentStagePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl RecruitmentStagePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct RecruitmentStagePaginatedResult {
    pub data: Vec<RecruitmentStage>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct RecruitmentStageFilter {
    pub company_id: Option<Uuid>,
    pub name: Option<String>,
    pub is_hired: Option<bool>,
    pub folded: Option<bool>,
    pub description: Option<String>,
}

impl RecruitmentStageFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.name.is_some() || self.is_hired.is_some() || self.folded.is_some() || self.description.is_some()
    }
}

/// Repository trait for RecruitmentStage aggregate
///
/// This trait defines the persistence contract for RecruitmentStage entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait RecruitmentStageRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new recruitment_stage entity
    async fn save(&self, entity: &RecruitmentStage) -> Result<RecruitmentStage>;

    /// Find recruitment_stage by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<RecruitmentStage>>;

    /// Find all recruitment_stage entities
    async fn find_all(&self) -> Result<Vec<RecruitmentStage>>;

    /// Update recruitment_stage by ID
    async fn update(&self, id: &str, entity: &RecruitmentStage) -> Result<Option<RecruitmentStage>>;

    /// Delete recruitment_stage by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List recruitment_stage with pagination
    async fn list(&self, params: RecruitmentStagePaginationParams) -> Result<RecruitmentStagePaginatedResult>;

    /// List recruitment_stage with pagination and filters
    async fn list_with_filters(&self, params: RecruitmentStagePaginationParams, filters: RecruitmentStageFilter) -> Result<RecruitmentStagePaginatedResult>;

    /// Count all recruitment_stage entities
    async fn count(&self) -> Result<u64>;

    /// Count recruitment_stage entities matching filters
    async fn count_with_filters(&self, filters: RecruitmentStageFilter) -> Result<u64>;

    /// Check if recruitment_stage exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete recruitment_stage by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted recruitment_stage by ID
    async fn restore(&self, id: &str) -> Result<Option<RecruitmentStage>>;

    /// List soft-deleted recruitment_stage entities
    async fn list_deleted(&self, params: RecruitmentStagePaginationParams) -> Result<RecruitmentStagePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save recruitment_stage entities
    async fn bulk_save(&self, entities: &[RecruitmentStage]) -> Result<Vec<RecruitmentStage>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
