//! Repository trait for RequisitionSkill aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the RequisitionSkill aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{RequisitionSkill, ProficiencyLevel};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct RequisitionSkillPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl RequisitionSkillPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct RequisitionSkillPaginatedResult {
    pub data: Vec<RequisitionSkill>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct RequisitionSkillFilter {
    pub company_id: Option<Uuid>,
    pub requisition_id: Option<Uuid>,
    pub skill_id: Option<Uuid>,
    pub required_proficiency: Option<ProficiencyLevel>,
}

impl RequisitionSkillFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.requisition_id.is_some() || self.skill_id.is_some() || self.required_proficiency.is_some()
    }
}

/// Repository trait for RequisitionSkill aggregate
///
/// This trait defines the persistence contract for RequisitionSkill entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait RequisitionSkillRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new requisition_skill entity
    async fn save(&self, entity: &RequisitionSkill) -> Result<RequisitionSkill>;

    /// Find requisition_skill by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<RequisitionSkill>>;

    /// Find all requisition_skill entities
    async fn find_all(&self) -> Result<Vec<RequisitionSkill>>;

    /// Update requisition_skill by ID
    async fn update(&self, id: &str, entity: &RequisitionSkill) -> Result<Option<RequisitionSkill>>;

    /// Delete requisition_skill by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List requisition_skill with pagination
    async fn list(&self, params: RequisitionSkillPaginationParams) -> Result<RequisitionSkillPaginatedResult>;

    /// List requisition_skill with pagination and filters
    async fn list_with_filters(&self, params: RequisitionSkillPaginationParams, filters: RequisitionSkillFilter) -> Result<RequisitionSkillPaginatedResult>;

    /// Count all requisition_skill entities
    async fn count(&self) -> Result<u64>;

    /// Count requisition_skill entities matching filters
    async fn count_with_filters(&self, filters: RequisitionSkillFilter) -> Result<u64>;

    /// Check if requisition_skill exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete requisition_skill by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted requisition_skill by ID
    async fn restore(&self, id: &str) -> Result<Option<RequisitionSkill>>;

    /// List soft-deleted requisition_skill entities
    async fn list_deleted(&self, params: RequisitionSkillPaginationParams) -> Result<RequisitionSkillPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save requisition_skill entities
    async fn bulk_save(&self, entities: &[RequisitionSkill]) -> Result<Vec<RequisitionSkill>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
