//! Repository for Candidate entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Candidate, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Candidate;

/// Table name for Candidate entities
pub const TABLE_NAME: &str = "recruitment.candidates";

/// Repository for Candidate entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct CandidateRepository(
    backbone_orm::GenericCrudRepository<Candidate, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for CandidateRepository {
    type Target = backbone_orm::GenericCrudRepository<Candidate, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl CandidateRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(CandidateRepository, Candidate, soft_delete);
