//! Repository for Interview entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Interview, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Interview;

/// Table name for Interview entities
pub const TABLE_NAME: &str = "recruitment.interviews";

/// Repository for Interview entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct InterviewRepository(
    backbone_orm::GenericCrudRepository<Interview, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for InterviewRepository {
    type Target = backbone_orm::GenericCrudRepository<Interview, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl InterviewRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(InterviewRepository, Interview, soft_delete);
