//! Repository for JobApplication entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<JobApplication, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::JobApplication;

/// Table name for JobApplication entities
pub const TABLE_NAME: &str = "recruitment.job_applications";

/// Repository for JobApplication entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct JobApplicationRepository(
    backbone_orm::GenericCrudRepository<JobApplication, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for JobApplicationRepository {
    type Target = backbone_orm::GenericCrudRepository<JobApplication, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl JobApplicationRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(JobApplicationRepository, JobApplication, soft_delete);
