//! Repository for JobOffer entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<JobOffer, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::JobOffer;

/// Table name for JobOffer entities
pub const TABLE_NAME: &str = "recruitment.job_offers";

/// Repository for JobOffer entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct JobOfferRepository(
    backbone_orm::GenericCrudRepository<JobOffer, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for JobOfferRepository {
    type Target = backbone_orm::GenericCrudRepository<JobOffer, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl JobOfferRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(JobOfferRepository, JobOffer, soft_delete);
