//! Repository for JobRequisition entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<JobRequisition, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::JobRequisition;

/// Table name for JobRequisition entities
pub const TABLE_NAME: &str = "recruitment.job_requisitions";

/// Repository for JobRequisition entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct JobRequisitionRepository(
    backbone_orm::GenericCrudRepository<JobRequisition, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for JobRequisitionRepository {
    type Target = backbone_orm::GenericCrudRepository<JobRequisition, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl JobRequisitionRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(JobRequisitionRepository, JobRequisition, soft_delete);
