//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod candidate_repository;
mod interview_repository;
mod job_application_repository;
mod job_offer_repository;
mod job_requisition_repository;

// Custom persistence modules
// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use candidate_repository::CandidateRepository;
pub use interview_repository::InterviewRepository;
pub use job_application_repository::JobApplicationRepository;
pub use job_offer_repository::JobOfferRepository;
pub use job_requisition_repository::JobRequisitionRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
// END CUSTOM
