//! Repository for OfferLetterTemplate entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<OfferLetterTemplate, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::OfferLetterTemplate;

/// Table name for OfferLetterTemplate entities
pub const TABLE_NAME: &str = "recruitment.offer_letter_templates";

/// Repository for OfferLetterTemplate entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct OfferLetterTemplateRepository(
    backbone_orm::GenericCrudRepository<OfferLetterTemplate, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for OfferLetterTemplateRepository {
    type Target = backbone_orm::GenericCrudRepository<OfferLetterTemplate, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl OfferLetterTemplateRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(OfferLetterTemplateRepository, OfferLetterTemplate, soft_delete);
