//! Repository for RecruitmentStage entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<RecruitmentStage, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::RecruitmentStage;

/// Table name for RecruitmentStage entities
pub const TABLE_NAME: &str = "recruitment.recruitment_stages";

/// Repository for RecruitmentStage entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct RecruitmentStageRepository(
    backbone_orm::GenericCrudRepository<RecruitmentStage, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for RecruitmentStageRepository {
    type Target = backbone_orm::GenericCrudRepository<RecruitmentStage, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl RecruitmentStageRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(RecruitmentStageRepository, RecruitmentStage, soft_delete);
