//! Repository for RequisitionSkill entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<RequisitionSkill, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::RequisitionSkill;

/// Table name for RequisitionSkill entities
pub const TABLE_NAME: &str = "recruitment.requisition_skills";

/// Repository for RequisitionSkill entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct RequisitionSkillRepository(
    backbone_orm::GenericCrudRepository<RequisitionSkill, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for RequisitionSkillRepository {
    type Target = backbone_orm::GenericCrudRepository<RequisitionSkill, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl RequisitionSkillRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(RequisitionSkillRepository, RequisitionSkill, soft_delete);
