//! Validator for Candidate entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Candidate>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::Candidate;

/// Validator type alias for Candidate entities.
pub type CandidateValidator = EntityValidator<Candidate>;

/// Build a validator for Candidate with all schema-defined field rules.
pub fn candidate_validator() -> CandidateValidator {
    EntityValidator::new()
        .rule(RequiredString::new("first_name", |e: &Candidate| &e.first_name))
        .rule(OptionalNotBlank::new("last_name", |e: &Candidate| e.last_name.as_deref()))
        .rule(OptionalNotBlank::new("email", |e: &Candidate| e.email.as_deref()))
        .rule(OptionalNotBlank::new("phone", |e: &Candidate| e.phone.as_deref()))
        .rule(OptionalNotBlank::new("current_employer", |e: &Candidate| e.current_employer.as_deref()))
        .rule(OptionalNotBlank::new("resume_url", |e: &Candidate| e.resume_url.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
