//! Validator for Interview entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Interview>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank};
use crate::domain::entity::Interview;

/// Validator type alias for Interview entities.
pub type InterviewValidator = EntityValidator<Interview>;

/// Build a validator for Interview with all schema-defined field rules.
pub fn interview_validator() -> InterviewValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("interview_format", |e: &Interview| e.interview_format.as_deref()))
        .rule(OptionalNotBlank::new("feedback", |e: &Interview| e.feedback.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
