//! Validator for JobApplication entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<JobApplication>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::JobApplication;

/// Validator type alias for JobApplication entities.
pub type JobApplicationValidator = EntityValidator<JobApplication>;

/// Build a validator for JobApplication with all schema-defined field rules.
pub fn job_application_validator() -> JobApplicationValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
