//! Validator for JobOffer entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<JobOffer>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank};
use crate::domain::entity::JobOffer;

/// Validator type alias for JobOffer entities.
pub type JobOfferValidator = EntityValidator<JobOffer>;

/// Build a validator for JobOffer with all schema-defined field rules.
pub fn job_offer_validator() -> JobOfferValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("employment_type", |e: &JobOffer| e.employment_type.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
