//! Validator for JobRequisition entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<JobRequisition>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredString};
use crate::domain::entity::JobRequisition;

/// Validator type alias for JobRequisition entities.
pub type JobRequisitionValidator = EntityValidator<JobRequisition>;

/// Build a validator for JobRequisition with all schema-defined field rules.
pub fn job_requisition_validator() -> JobRequisitionValidator {
    EntityValidator::new()
        .rule(RequiredString::new("title", |e: &JobRequisition| &e.title))
        .rule(NonNegative::new("headcount", |e: &JobRequisition| e.headcount as i64))
        .rule(NonNegative::new("filled_headcount", |e: &JobRequisition| e.filled_headcount as i64))
        .rule(OptionalNotBlank::new("employment_type", |e: &JobRequisition| e.employment_type.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
