//! Validator for OfferLetterTemplate entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<OfferLetterTemplate>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::OfferLetterTemplate;

/// Validator type alias for OfferLetterTemplate entities.
pub type OfferLetterTemplateValidator = EntityValidator<OfferLetterTemplate>;

/// Build a validator for OfferLetterTemplate with all schema-defined field rules.
pub fn offer_letter_template_validator() -> OfferLetterTemplateValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &OfferLetterTemplate| &e.name))
        .rule(RequiredString::new("subject", |e: &OfferLetterTemplate| &e.subject))
        .rule(RequiredString::new("body", |e: &OfferLetterTemplate| &e.body))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
