//! Validator for RecruitmentStage entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<RecruitmentStage>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredString};
use crate::domain::entity::RecruitmentStage;

/// Validator type alias for RecruitmentStage entities.
pub type RecruitmentStageValidator = EntityValidator<RecruitmentStage>;

/// Build a validator for RecruitmentStage with all schema-defined field rules.
pub fn recruitment_stage_validator() -> RecruitmentStageValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &RecruitmentStage| &e.name))
        .rule(NonNegative::new("sequence", |e: &RecruitmentStage| e.sequence as i64))
        .rule(OptionalNotBlank::new("description", |e: &RecruitmentStage| e.description.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
