//! Validator for RequisitionSkill entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<RequisitionSkill>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::RequisitionSkill;

/// Validator type alias for RequisitionSkill entities.
pub type RequisitionSkillValidator = EntityValidator<RequisitionSkill>;

/// Build a validator for RequisitionSkill with all schema-defined field rules.
pub fn requisition_skill_validator() -> RequisitionSkillValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
