//! Auth configuration for Candidate handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Candidate>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::CandidateService;
use crate::domain::entity::Candidate;

/// Permission string constants for Candidate operations.
pub mod permissions {
    pub const LIST:        &str = "candidate:list";
    pub const READ:        &str = "candidate:read";
    pub const CREATE:      &str = "candidate:create";
    pub const UPDATE:      &str = "candidate:update";
    pub const DELETE:      &str = "candidate:delete";
    pub const RESTORE:     &str = "candidate:restore";
    pub const TRASH:       &str = "candidate:trash";
    pub const EMPTY_TRASH: &str = "candidate:empty_trash";
    pub const BULK_CREATE: &str = "candidate:bulk_create";
    pub const UPSERT:      &str = "candidate:upsert";
}

/// Resource policy for Candidate — maps CRUD actions to permission strings.
pub struct CandidatePolicy;

#[async_trait]
impl ResourcePolicy<Candidate> for CandidatePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Candidate,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Candidate handlers.
///
/// Wraps `CandidateService` and checks `CandidatePolicy` before delegating.
pub type CandidateGuard = PermissionGuard<Candidate>;

/// Service-integrated permission guard for Candidate (for use in generated handlers).
pub type CandidateServiceGuard = ServicePermissionGuard<Candidate, CandidateService, CandidatePolicy>;

// <<< CUSTOM
// END CUSTOM
