//! Auth configuration for Interview handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Interview>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::InterviewService;
use crate::domain::entity::Interview;

/// Permission string constants for Interview operations.
pub mod permissions {
    pub const LIST:        &str = "interview:list";
    pub const READ:        &str = "interview:read";
    pub const CREATE:      &str = "interview:create";
    pub const UPDATE:      &str = "interview:update";
    pub const DELETE:      &str = "interview:delete";
    pub const RESTORE:     &str = "interview:restore";
    pub const TRASH:       &str = "interview:trash";
    pub const EMPTY_TRASH: &str = "interview:empty_trash";
    pub const BULK_CREATE: &str = "interview:bulk_create";
    pub const UPSERT:      &str = "interview:upsert";
}

/// Resource policy for Interview — maps CRUD actions to permission strings.
pub struct InterviewPolicy;

#[async_trait]
impl ResourcePolicy<Interview> for InterviewPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Interview,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Interview handlers.
///
/// Wraps `InterviewService` and checks `InterviewPolicy` before delegating.
pub type InterviewGuard = PermissionGuard<Interview>;

/// Service-integrated permission guard for Interview (for use in generated handlers).
pub type InterviewServiceGuard = ServicePermissionGuard<Interview, InterviewService, InterviewPolicy>;

// <<< CUSTOM
// END CUSTOM
