//! Auth configuration for JobApplication handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<JobApplication>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::JobApplicationService;
use crate::domain::entity::JobApplication;

/// Permission string constants for JobApplication operations.
pub mod permissions {
    pub const LIST:        &str = "job_application:list";
    pub const READ:        &str = "job_application:read";
    pub const CREATE:      &str = "job_application:create";
    pub const UPDATE:      &str = "job_application:update";
    pub const DELETE:      &str = "job_application:delete";
    pub const RESTORE:     &str = "job_application:restore";
    pub const TRASH:       &str = "job_application:trash";
    pub const EMPTY_TRASH: &str = "job_application:empty_trash";
    pub const BULK_CREATE: &str = "job_application:bulk_create";
    pub const UPSERT:      &str = "job_application:upsert";
}

/// Resource policy for JobApplication — maps CRUD actions to permission strings.
pub struct JobApplicationPolicy;

#[async_trait]
impl ResourcePolicy<JobApplication> for JobApplicationPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &JobApplication,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for JobApplication handlers.
///
/// Wraps `JobApplicationService` and checks `JobApplicationPolicy` before delegating.
pub type JobApplicationGuard = PermissionGuard<JobApplication>;

/// Service-integrated permission guard for JobApplication (for use in generated handlers).
pub type JobApplicationServiceGuard = ServicePermissionGuard<JobApplication, JobApplicationService, JobApplicationPolicy>;

// <<< CUSTOM
// END CUSTOM
