//! Auth configuration for JobOffer handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<JobOffer>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::JobOfferService;
use crate::domain::entity::JobOffer;

/// Permission string constants for JobOffer operations.
pub mod permissions {
    pub const LIST:        &str = "job_offer:list";
    pub const READ:        &str = "job_offer:read";
    pub const CREATE:      &str = "job_offer:create";
    pub const UPDATE:      &str = "job_offer:update";
    pub const DELETE:      &str = "job_offer:delete";
    pub const RESTORE:     &str = "job_offer:restore";
    pub const TRASH:       &str = "job_offer:trash";
    pub const EMPTY_TRASH: &str = "job_offer:empty_trash";
    pub const BULK_CREATE: &str = "job_offer:bulk_create";
    pub const UPSERT:      &str = "job_offer:upsert";
}

/// Resource policy for JobOffer — maps CRUD actions to permission strings.
pub struct JobOfferPolicy;

#[async_trait]
impl ResourcePolicy<JobOffer> for JobOfferPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &JobOffer,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for JobOffer handlers.
///
/// Wraps `JobOfferService` and checks `JobOfferPolicy` before delegating.
pub type JobOfferGuard = PermissionGuard<JobOffer>;

/// Service-integrated permission guard for JobOffer (for use in generated handlers).
pub type JobOfferServiceGuard = ServicePermissionGuard<JobOffer, JobOfferService, JobOfferPolicy>;

// <<< CUSTOM
// END CUSTOM
