//! Auth configuration for JobRequisition handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<JobRequisition>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::JobRequisitionService;
use crate::domain::entity::JobRequisition;

/// Permission string constants for JobRequisition operations.
pub mod permissions {
    pub const LIST:        &str = "job_requisition:list";
    pub const READ:        &str = "job_requisition:read";
    pub const CREATE:      &str = "job_requisition:create";
    pub const UPDATE:      &str = "job_requisition:update";
    pub const DELETE:      &str = "job_requisition:delete";
    pub const RESTORE:     &str = "job_requisition:restore";
    pub const TRASH:       &str = "job_requisition:trash";
    pub const EMPTY_TRASH: &str = "job_requisition:empty_trash";
    pub const BULK_CREATE: &str = "job_requisition:bulk_create";
    pub const UPSERT:      &str = "job_requisition:upsert";
}

/// Resource policy for JobRequisition — maps CRUD actions to permission strings.
pub struct JobRequisitionPolicy;

#[async_trait]
impl ResourcePolicy<JobRequisition> for JobRequisitionPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &JobRequisition,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for JobRequisition handlers.
///
/// Wraps `JobRequisitionService` and checks `JobRequisitionPolicy` before delegating.
pub type JobRequisitionGuard = PermissionGuard<JobRequisition>;

/// Service-integrated permission guard for JobRequisition (for use in generated handlers).
pub type JobRequisitionServiceGuard = ServicePermissionGuard<JobRequisition, JobRequisitionService, JobRequisitionPolicy>;

// <<< CUSTOM
// END CUSTOM
