//! Auth policies and guards
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod candidate_auth;
pub mod interview_auth;
pub mod job_application_auth;
pub mod job_offer_auth;
pub mod job_requisition_auth;

pub use candidate_auth::{CandidatePolicy, CandidateGuard, CandidateServiceGuard};
pub use interview_auth::{InterviewPolicy, InterviewGuard, InterviewServiceGuard};
pub use job_application_auth::{JobApplicationPolicy, JobApplicationGuard, JobApplicationServiceGuard};
pub use job_offer_auth::{JobOfferPolicy, JobOfferGuard, JobOfferServiceGuard};
pub use job_requisition_auth::{JobRequisitionPolicy, JobRequisitionGuard, JobRequisitionServiceGuard};

// <<< CUSTOM
// END CUSTOM
