//! Candidate API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Candidate CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// CANDIDATE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Candidate
pub struct CandidateTestData;

impl TestDataGenerator for CandidateTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "first_name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "last_name": null,
            "email": null,
            "phone": null,
            "source": null,
            "current_employer": null,
            "resume_url": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "first_name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "last_name": null,
            "email": null,
            "phone": null,
            "source": null,
            "current_employer": null,
            "resume_url": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// CANDIDATE API TEST
// ============================================================================

/// Candidate API test suite
pub struct CandidateApiTest {
    inner: GenericCrudTest<CandidateTestData>,
}

impl CandidateApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/candidates", "Candidate");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, CandidateTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for CandidateApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_candidate_crud() {
        let mut test = CandidateApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Candidate specific tests here
// <<< CUSTOM TESTS END >>>
