//! Interview API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Interview CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// INTERVIEW TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Interview
pub struct InterviewTestData;

impl TestDataGenerator for InterviewTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "application_id": Uuid::new_v4().to_string(),
            "interviewer_id": Uuid::new_v4().to_string(),
            "scheduled_at": now,
            "round": null,
            "interview_format": null,
            "rating": null,
            "feedback": null,
            "status": "scheduled",
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "application_id": Uuid::new_v4().to_string(),
            "interviewer_id": Uuid::new_v4().to_string(),
            "scheduled_at": now,
            "round": null,
            "interview_format": null,
            "rating": null,
            "feedback": null,
            "status": "scheduled",
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/job_applications", &super::job_application_api_test::JobApplicationTestData).await {
            deps.push(("application_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// INTERVIEW API TEST
// ============================================================================

/// Interview API test suite
pub struct InterviewApiTest {
    inner: GenericCrudTest<InterviewTestData>,
}

impl InterviewApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/interviews", "Interview");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, InterviewTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for InterviewApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_interview_crud() {
        let mut test = InterviewApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Interview specific tests here
// <<< CUSTOM TESTS END >>>
