//! JobApplication API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the JobApplication CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// JOBAPPLICATION TEST DATA GENERATOR
// ============================================================================

/// Test data generator for JobApplication
pub struct JobApplicationTestData;

impl TestDataGenerator for JobApplicationTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "candidate_id": Uuid::new_v4().to_string(),
            "requisition_id": Uuid::new_v4().to_string(),
            "status": "applied",
            "applied_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "candidate_id": Uuid::new_v4().to_string(),
            "requisition_id": Uuid::new_v4().to_string(),
            "status": "applied",
            "applied_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/candidates", &super::candidate_api_test::CandidateTestData).await {
            deps.push(("candidate_id".to_string(), id));
        }
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/job_requisitions", &super::job_requisition_api_test::JobRequisitionTestData).await {
            deps.push(("requisition_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// JOBAPPLICATION API TEST
// ============================================================================

/// JobApplication API test suite
pub struct JobApplicationApiTest {
    inner: GenericCrudTest<JobApplicationTestData>,
}

impl JobApplicationApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/job_applications", "JobApplication");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, JobApplicationTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for JobApplicationApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_job_application_crud() {
        let mut test = JobApplicationApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add JobApplication specific tests here
// <<< CUSTOM TESTS END >>>
