//! JobRequisition API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the JobRequisition CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// JOBREQUISITION TEST DATA GENERATOR
// ============================================================================

/// Test data generator for JobRequisition
pub struct JobRequisitionTestData;

impl TestDataGenerator for JobRequisitionTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "department_id": null,
            "position_id": null,
            "title": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "headcount": 1,
            "employment_type": null,
            "status": "draft",
            "opened_by": Uuid::new_v4().to_string(),
            "budget": null,
            "deadline": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "department_id": null,
            "position_id": null,
            "title": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "headcount": 1,
            "employment_type": null,
            "status": "draft",
            "opened_by": Uuid::new_v4().to_string(),
            "budget": null,
            "deadline": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// JOBREQUISITION API TEST
// ============================================================================

/// JobRequisition API test suite
pub struct JobRequisitionApiTest {
    inner: GenericCrudTest<JobRequisitionTestData>,
}

impl JobRequisitionApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/job_requisitions", "JobRequisition");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, JobRequisitionTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for JobRequisitionApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_job_requisition_crud() {
        let mut test = JobRequisitionApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add JobRequisition specific tests here
// <<< CUSTOM TESTS END >>>
