//! Integration Test Implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Contains CRUD API tests for all entities.

pub mod crud_test_base;

pub mod candidate_api_test;
pub mod interview_api_test;
pub mod job_application_api_test;
pub mod job_offer_api_test;
pub mod job_requisition_api_test;

// Re-exports for convenience
pub use crud_test_base::*;
pub use candidate_api_test::*;
pub use interview_api_test::*;
pub use job_application_api_test::*;
pub use job_offer_api_test::*;
pub use job_requisition_api_test::*;
