//! RecruitmentStage API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the RecruitmentStage CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// RECRUITMENTSTAGE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for RecruitmentStage
pub struct RecruitmentStageTestData;

impl TestDataGenerator for RecruitmentStageTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "sequence": 1,
            "is_hired": false,
            "folded": false,
            "description": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "sequence": 1,
            "is_hired": false,
            "folded": false,
            "description": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// RECRUITMENTSTAGE API TEST
// ============================================================================

/// RecruitmentStage API test suite
pub struct RecruitmentStageApiTest {
    inner: GenericCrudTest<RecruitmentStageTestData>,
}

impl RecruitmentStageApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/recruitment_stages", "RecruitmentStage");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, RecruitmentStageTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for RecruitmentStageApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_recruitment_stage_crud() {
        let mut test = RecruitmentStageApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add RecruitmentStage specific tests here
// <<< CUSTOM TESTS END >>>
