//! RequisitionSkill API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the RequisitionSkill CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// REQUISITIONSKILL TEST DATA GENERATOR
// ============================================================================

/// Test data generator for RequisitionSkill
pub struct RequisitionSkillTestData;

impl TestDataGenerator for RequisitionSkillTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "requisition_id": Uuid::new_v4().to_string(),
            "skill_id": Uuid::new_v4().to_string(),
            "required_proficiency": "novice",
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "requisition_id": Uuid::new_v4().to_string(),
            "skill_id": Uuid::new_v4().to_string(),
            "required_proficiency": "novice",
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/job_requisitions", &super::job_requisition_api_test::JobRequisitionTestData).await {
            deps.push(("requisition_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// REQUISITIONSKILL API TEST
// ============================================================================

/// RequisitionSkill API test suite
pub struct RequisitionSkillApiTest {
    inner: GenericCrudTest<RequisitionSkillTestData>,
}

impl RequisitionSkillApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/requisition_skills", "RequisitionSkill");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, RequisitionSkillTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for RequisitionSkillApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_requisition_skill_crud() {
        let mut test = RequisitionSkillApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add RequisitionSkill specific tests here
// <<< CUSTOM TESTS END >>>
