//! Recruitment Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::CandidateService;
use crate::application::service::InterviewService;
use crate::application::service::JobApplicationService;
use crate::application::service::JobOfferService;
use crate::application::service::JobRequisitionService;
use crate::application::service::OfferLetterTemplateService;
use crate::application::service::RecruitmentStageService;
use crate::application::service::RequisitionSkillService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// Candidate service
    pub candidate_service: Arc<CandidateService>,
    /// Interview service
    pub interview_service: Arc<InterviewService>,
    /// JobApplication service
    pub job_application_service: Arc<JobApplicationService>,
    /// JobOffer service
    pub job_offer_service: Arc<JobOfferService>,
    /// JobRequisition service
    pub job_requisition_service: Arc<JobRequisitionService>,
    /// OfferLetterTemplate service
    pub offer_letter_template_service: Arc<OfferLetterTemplateService>,
    /// RecruitmentStage service
    pub recruitment_stage_service: Arc<RecruitmentStageService>,
    /// RequisitionSkill service
    pub requisition_skill_service: Arc<RequisitionSkillService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        candidate_service: Arc<CandidateService>,
        interview_service: Arc<InterviewService>,
        job_application_service: Arc<JobApplicationService>,
        job_offer_service: Arc<JobOfferService>,
        job_requisition_service: Arc<JobRequisitionService>,
        offer_letter_template_service: Arc<OfferLetterTemplateService>,
        recruitment_stage_service: Arc<RecruitmentStageService>,
        requisition_skill_service: Arc<RequisitionSkillService>
    ) -> Self {
        Self {
            candidate_service,
            interview_service,
            job_application_service,
            job_offer_service,
            job_requisition_service,
            offer_letter_template_service,
            recruitment_stage_service,
            requisition_skill_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::RecruitmentModule) -> Self {
        Self {
            candidate_service: module.candidate_service.clone(),
            interview_service: module.interview_service.clone(),
            job_application_service: module.job_application_service.clone(),
            job_offer_service: module.job_offer_service.clone(),
            job_requisition_service: module.job_requisition_service.clone(),
            offer_letter_template_service: module.offer_letter_template_service.clone(),
            recruitment_stage_service: module.recruitment_stage_service.clone(),
            requisition_skill_service: module.requisition_skill_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    candidate_service: Option<Arc<CandidateService>>,
    interview_service: Option<Arc<InterviewService>>,
    job_application_service: Option<Arc<JobApplicationService>>,
    job_offer_service: Option<Arc<JobOfferService>>,
    job_requisition_service: Option<Arc<JobRequisitionService>>,
    offer_letter_template_service: Option<Arc<OfferLetterTemplateService>>,
    recruitment_stage_service: Option<Arc<RecruitmentStageService>>,
    requisition_skill_service: Option<Arc<RequisitionSkillService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the Candidate service.
    pub fn with_candidate_service(mut self, service: Arc<CandidateService>) -> Self {
        self.candidate_service = Some(service);
        self
    }

    /// Set the Interview service.
    pub fn with_interview_service(mut self, service: Arc<InterviewService>) -> Self {
        self.interview_service = Some(service);
        self
    }

    /// Set the JobApplication service.
    pub fn with_job_application_service(mut self, service: Arc<JobApplicationService>) -> Self {
        self.job_application_service = Some(service);
        self
    }

    /// Set the JobOffer service.
    pub fn with_job_offer_service(mut self, service: Arc<JobOfferService>) -> Self {
        self.job_offer_service = Some(service);
        self
    }

    /// Set the JobRequisition service.
    pub fn with_job_requisition_service(mut self, service: Arc<JobRequisitionService>) -> Self {
        self.job_requisition_service = Some(service);
        self
    }

    /// Set the OfferLetterTemplate service.
    pub fn with_offer_letter_template_service(mut self, service: Arc<OfferLetterTemplateService>) -> Self {
        self.offer_letter_template_service = Some(service);
        self
    }

    /// Set the RecruitmentStage service.
    pub fn with_recruitment_stage_service(mut self, service: Arc<RecruitmentStageService>) -> Self {
        self.recruitment_stage_service = Some(service);
        self
    }

    /// Set the RequisitionSkill service.
    pub fn with_requisition_skill_service(mut self, service: Arc<RequisitionSkillService>) -> Self {
        self.requisition_skill_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            candidate_service: self.candidate_service.expect("candidate_service is required"),
            interview_service: self.interview_service.expect("interview_service is required"),
            job_application_service: self.job_application_service.expect("job_application_service is required"),
            job_offer_service: self.job_offer_service.expect("job_offer_service is required"),
            job_requisition_service: self.job_requisition_service.expect("job_requisition_service is required"),
            offer_letter_template_service: self.offer_letter_template_service.expect("offer_letter_template_service is required"),
            recruitment_stage_service: self.recruitment_stage_service.expect("recruitment_stage_service is required"),
            requisition_skill_service: self.requisition_skill_service.expect("requisition_skill_service is required"),
        }
    }
}
