//! Recruitment Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::CandidateService;
use crate::application::service::InterviewService;
use crate::application::service::JobApplicationService;
use crate::application::service::JobOfferService;
use crate::application::service::JobRequisitionService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// Candidate service
    pub candidate_service: Arc<CandidateService>,
    /// Interview service
    pub interview_service: Arc<InterviewService>,
    /// JobApplication service
    pub job_application_service: Arc<JobApplicationService>,
    /// JobOffer service
    pub job_offer_service: Arc<JobOfferService>,
    /// JobRequisition service
    pub job_requisition_service: Arc<JobRequisitionService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        candidate_service: Arc<CandidateService>,
        interview_service: Arc<InterviewService>,
        job_application_service: Arc<JobApplicationService>,
        job_offer_service: Arc<JobOfferService>,
        job_requisition_service: Arc<JobRequisitionService>
    ) -> Self {
        Self {
            candidate_service,
            interview_service,
            job_application_service,
            job_offer_service,
            job_requisition_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::RecruitmentModule) -> Self {
        Self {
            candidate_service: module.candidate_service.clone(),
            interview_service: module.interview_service.clone(),
            job_application_service: module.job_application_service.clone(),
            job_offer_service: module.job_offer_service.clone(),
            job_requisition_service: module.job_requisition_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    candidate_service: Option<Arc<CandidateService>>,
    interview_service: Option<Arc<InterviewService>>,
    job_application_service: Option<Arc<JobApplicationService>>,
    job_offer_service: Option<Arc<JobOfferService>>,
    job_requisition_service: Option<Arc<JobRequisitionService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the Candidate service.
    pub fn with_candidate_service(mut self, service: Arc<CandidateService>) -> Self {
        self.candidate_service = Some(service);
        self
    }

    /// Set the Interview service.
    pub fn with_interview_service(mut self, service: Arc<InterviewService>) -> Self {
        self.interview_service = Some(service);
        self
    }

    /// Set the JobApplication service.
    pub fn with_job_application_service(mut self, service: Arc<JobApplicationService>) -> Self {
        self.job_application_service = Some(service);
        self
    }

    /// Set the JobOffer service.
    pub fn with_job_offer_service(mut self, service: Arc<JobOfferService>) -> Self {
        self.job_offer_service = Some(service);
        self
    }

    /// Set the JobRequisition service.
    pub fn with_job_requisition_service(mut self, service: Arc<JobRequisitionService>) -> Self {
        self.job_requisition_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            candidate_service: self.candidate_service.expect("candidate_service is required"),
            interview_service: self.interview_service.expect("interview_service is required"),
            job_application_service: self.job_application_service.expect("job_application_service is required"),
            job_offer_service: self.job_offer_service.expect("job_offer_service is required"),
            job_requisition_service: self.job_requisition_service.expect("job_requisition_service is required"),
        }
    }
}
