//! Workflows (saga / orchestration patterns)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Reserved for saga-style orchestration. No workflows defined yet for this
//! module — the hire handoff is emitted via the outbox, not a saga (matches
//! the lifecycle module's deferred cross-module event pattern).

// <<< CUSTOM
// END CUSTOM
