//! HTTP route configuration
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides consolidated Axum route configuration using backbone-core's
//! BackboneCrudHandler for all 12 standard Backbone CRUD endpoints per entity.

use axum::Router;
use std::sync::Arc;

use super::{
    candidate_handler::create_candidate_routes,
    interview_handler::create_interview_routes,
    job_application_handler::create_job_application_routes,
    job_offer_handler::create_job_offer_routes,
    job_requisition_handler::create_job_requisition_routes,
    offer_letter_template_handler::create_offer_letter_template_routes,
    recruitment_stage_handler::create_recruitment_stage_routes,
    requisition_skill_handler::create_requisition_skill_routes,
};

use crate::application::service::{
    CandidateService,
    InterviewService,
    JobApplicationService,
    JobOfferService,
    JobRequisitionService,
    OfferLetterTemplateService,
    RecruitmentStageService,
    RequisitionSkillService,
};

/// Services collection for all CRUD endpoints
pub struct HttpServices {
    pub candidate: Arc<CandidateService>,
    pub interview: Arc<InterviewService>,
    pub job_application: Arc<JobApplicationService>,
    pub job_offer: Arc<JobOfferService>,
    pub job_requisition: Arc<JobRequisitionService>,
    pub offer_letter_template: Arc<OfferLetterTemplateService>,
    pub recruitment_stage: Arc<RecruitmentStageService>,
    pub requisition_skill: Arc<RequisitionSkillService>,
}

/// Configure all HTTP routes for this module using Axum and BackboneCrudHandler.
///
/// Each entity gets 12 standard Backbone CRUD endpoints:
/// 1. GET /api/v1/{collection} - List with pagination
/// 2. POST /api/v1/{collection} - Create
/// 3. GET /api/v1/{collection}/:id - Get by ID
/// 4. PUT /api/v1/{collection}/:id - Full update
/// 5. PATCH /api/v1/{collection}/:id - Partial update
/// 6. DELETE /api/v1/{collection}/:id - Soft delete
/// 7. POST /api/v1/{collection}/bulk - Bulk create
/// 8. POST /api/v1/{collection}/upsert - Upsert
/// 9. GET /api/v1/{collection}/trash - List deleted
/// 10. POST /api/v1/{collection}/:id/restore - Restore
/// 11. DELETE /api/v1/{collection}/empty - Empty trash
/// 12. GET /api/v1/{collection}/:id/deleted - Get deleted by ID
pub fn configure_routes(services: HttpServices) -> Router {
    Router::new()
        // Candidate routes (12 Backbone endpoints)
        .merge(create_candidate_routes(services.candidate))
        // Interview routes (12 Backbone endpoints)
        .merge(create_interview_routes(services.interview))
        // JobApplication routes (12 Backbone endpoints)
        .merge(create_job_application_routes(services.job_application))
        // JobOffer routes (12 Backbone endpoints)
        .merge(create_job_offer_routes(services.job_offer))
        // JobRequisition routes (12 Backbone endpoints)
        .merge(create_job_requisition_routes(services.job_requisition))
        // OfferLetterTemplate routes (12 Backbone endpoints)
        .merge(create_offer_letter_template_routes(services.offer_letter_template))
        // RecruitmentStage routes (12 Backbone endpoints)
        .merge(create_recruitment_stage_routes(services.recruitment_stage))
        // RequisitionSkill routes (12 Backbone endpoints)
        .merge(create_requisition_skill_routes(services.requisition_skill))
}

/// Create an individual entity's routes (for modular configuration)
pub mod individual {
    use super::*;

    pub fn candidate_routes(service: Arc<CandidateService>) -> Router {
        create_candidate_routes(service)
    }

    pub fn interview_routes(service: Arc<InterviewService>) -> Router {
        create_interview_routes(service)
    }

    pub fn job_application_routes(service: Arc<JobApplicationService>) -> Router {
        create_job_application_routes(service)
    }

    pub fn job_offer_routes(service: Arc<JobOfferService>) -> Router {
        create_job_offer_routes(service)
    }

    pub fn job_requisition_routes(service: Arc<JobRequisitionService>) -> Router {
        create_job_requisition_routes(service)
    }

    pub fn offer_letter_template_routes(service: Arc<OfferLetterTemplateService>) -> Router {
        create_offer_letter_template_routes(service)
    }

    pub fn recruitment_stage_routes(service: Arc<RecruitmentStageService>) -> Router {
        create_recruitment_stage_routes(service)
    }

    pub fn requisition_skill_routes(service: Arc<RequisitionSkillService>) -> Router {
        create_requisition_skill_routes(service)
    }

}
