//! Public events for Recruitment module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// CANDIDATE EVENTS
// ============================================================================

/// Event published when a Candidate is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CandidateCreatedEvent {
    pub id: CandidateId,
    pub data: CandidateDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Candidate is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CandidateUpdatedEvent {
    pub id: CandidateId,
    pub data: CandidateDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Candidate is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CandidateDeletedEvent {
    pub id: CandidateId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// INTERVIEW EVENTS
// ============================================================================

/// Event published when a Interview is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InterviewCreatedEvent {
    pub id: InterviewId,
    pub data: InterviewDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Interview is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InterviewUpdatedEvent {
    pub id: InterviewId,
    pub data: InterviewDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Interview is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InterviewDeletedEvent {
    pub id: InterviewId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// JOBAPPLICATION EVENTS
// ============================================================================

/// Event published when a JobApplication is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JobApplicationCreatedEvent {
    pub id: JobApplicationId,
    pub data: JobApplicationDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a JobApplication is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JobApplicationUpdatedEvent {
    pub id: JobApplicationId,
    pub data: JobApplicationDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a JobApplication is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JobApplicationDeletedEvent {
    pub id: JobApplicationId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// JOBOFFER EVENTS
// ============================================================================

/// Event published when a JobOffer is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JobOfferCreatedEvent {
    pub id: JobOfferId,
    pub data: JobOfferDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a JobOffer is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JobOfferUpdatedEvent {
    pub id: JobOfferId,
    pub data: JobOfferDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a JobOffer is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JobOfferDeletedEvent {
    pub id: JobOfferId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// JOBREQUISITION EVENTS
// ============================================================================

/// Event published when a JobRequisition is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JobRequisitionCreatedEvent {
    pub id: JobRequisitionId,
    pub data: JobRequisitionDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a JobRequisition is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JobRequisitionUpdatedEvent {
    pub id: JobRequisitionId,
    pub data: JobRequisitionDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a JobRequisition is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JobRequisitionDeletedEvent {
    pub id: JobRequisitionId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// OFFERLETTERTEMPLATE EVENTS
// ============================================================================

/// Event published when a OfferLetterTemplate is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OfferLetterTemplateCreatedEvent {
    pub id: OfferLetterTemplateId,
    pub data: OfferLetterTemplateDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a OfferLetterTemplate is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OfferLetterTemplateUpdatedEvent {
    pub id: OfferLetterTemplateId,
    pub data: OfferLetterTemplateDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a OfferLetterTemplate is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OfferLetterTemplateDeletedEvent {
    pub id: OfferLetterTemplateId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// RECRUITMENTSTAGE EVENTS
// ============================================================================

/// Event published when a RecruitmentStage is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RecruitmentStageCreatedEvent {
    pub id: RecruitmentStageId,
    pub data: RecruitmentStageDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a RecruitmentStage is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RecruitmentStageUpdatedEvent {
    pub id: RecruitmentStageId,
    pub data: RecruitmentStageDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a RecruitmentStage is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RecruitmentStageDeletedEvent {
    pub id: RecruitmentStageId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// REQUISITIONSKILL EVENTS
// ============================================================================

/// Event published when a RequisitionSkill is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RequisitionSkillCreatedEvent {
    pub id: RequisitionSkillId,
    pub data: RequisitionSkillDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a RequisitionSkill is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RequisitionSkillUpdatedEvent {
    pub id: RequisitionSkillId,
    pub data: RequisitionSkillDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a RequisitionSkill is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RequisitionSkillDeletedEvent {
    pub id: RequisitionSkillId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Recruitment module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum RecruitmentEvent {
    CandidateCreated(CandidateCreatedEvent),
    CandidateUpdated(CandidateUpdatedEvent),
    CandidateDeleted(CandidateDeletedEvent),
    InterviewCreated(InterviewCreatedEvent),
    InterviewUpdated(InterviewUpdatedEvent),
    InterviewDeleted(InterviewDeletedEvent),
    JobApplicationCreated(JobApplicationCreatedEvent),
    JobApplicationUpdated(JobApplicationUpdatedEvent),
    JobApplicationDeleted(JobApplicationDeletedEvent),
    JobOfferCreated(JobOfferCreatedEvent),
    JobOfferUpdated(JobOfferUpdatedEvent),
    JobOfferDeleted(JobOfferDeletedEvent),
    JobRequisitionCreated(JobRequisitionCreatedEvent),
    JobRequisitionUpdated(JobRequisitionUpdatedEvent),
    JobRequisitionDeleted(JobRequisitionDeletedEvent),
    OfferLetterTemplateCreated(OfferLetterTemplateCreatedEvent),
    OfferLetterTemplateUpdated(OfferLetterTemplateUpdatedEvent),
    OfferLetterTemplateDeleted(OfferLetterTemplateDeletedEvent),
    RecruitmentStageCreated(RecruitmentStageCreatedEvent),
    RecruitmentStageUpdated(RecruitmentStageUpdatedEvent),
    RecruitmentStageDeleted(RecruitmentStageDeletedEvent),
    RequisitionSkillCreated(RequisitionSkillCreatedEvent),
    RequisitionSkillUpdated(RequisitionSkillUpdatedEvent),
    RequisitionSkillDeleted(RequisitionSkillDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RecruitmentEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for RecruitmentEventMetadata {
    fn default() -> Self {
        Self {
            module: "recruitment",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
