//! Recruitment Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Recruitment exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use recruitment::exports::{CandidateDto, RecruitmentQueryService};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `CandidateDto` - Data transfer object for Candidate
/// - `CandidateSummary` - Summary view of Candidate
/// - `CandidateId` - Type-safe ID wrapper
/// - `InterviewDto` - Data transfer object for Interview
/// - `InterviewSummary` - Summary view of Interview
/// - `InterviewId` - Type-safe ID wrapper
/// - `JobApplicationDto` - Data transfer object for JobApplication
/// - `JobApplicationSummary` - Summary view of JobApplication
/// - `JobApplicationId` - Type-safe ID wrapper
/// - `JobOfferDto` - Data transfer object for JobOffer
/// - `JobOfferSummary` - Summary view of JobOffer
/// - `JobOfferId` - Type-safe ID wrapper
/// - `JobRequisitionDto` - Data transfer object for JobRequisition
/// - `JobRequisitionSummary` - Summary view of JobRequisition
/// - `JobRequisitionId` - Type-safe ID wrapper
///
/// ## Public Services
/// - `RecruitmentQueryService` - Read-only queries
///
/// ## Public Events
/// - `CandidateCreatedEvent` - Published when Candidate is created
/// - `CandidateUpdatedEvent` - Published when Candidate is updated
/// - `CandidateDeletedEvent` - Published when Candidate is deleted
/// - `InterviewCreatedEvent` - Published when Interview is created
/// - `InterviewUpdatedEvent` - Published when Interview is updated
/// - `InterviewDeletedEvent` - Published when Interview is deleted
/// - `JobApplicationCreatedEvent` - Published when JobApplication is created
/// - `JobApplicationUpdatedEvent` - Published when JobApplication is updated
/// - `JobApplicationDeletedEvent` - Published when JobApplication is deleted
/// - `JobOfferCreatedEvent` - Published when JobOffer is created
/// - `JobOfferUpdatedEvent` - Published when JobOffer is updated
/// - `JobOfferDeletedEvent` - Published when JobOffer is deleted
/// - `JobRequisitionCreatedEvent` - Published when JobRequisition is created
/// - `JobRequisitionUpdatedEvent` - Published when JobRequisition is updated
/// - `JobRequisitionDeletedEvent` - Published when JobRequisition is deleted
pub struct ExportSummary;
