//! Public types for Recruitment module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;
use crate::domain::entity::*;

// ============================================================================
// CANDIDATE TYPES
// ============================================================================

/// Type-safe ID for Candidate
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct CandidateId(pub Uuid);

impl CandidateId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for CandidateId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<CandidateId> for Uuid {
    fn from(id: CandidateId) -> Self {
        id.0
    }
}

/// Data transfer object for Candidate
///
/// This is the public representation of Candidate for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CandidateDto {
    pub id: CandidateId,
    pub company_id: Uuid,
    pub first_name: String,
    pub last_name: Option<String>,
    pub email: Option<String>,
    pub phone: Option<String>,
    pub source: Option<CandidateSource>,
    pub current_employer: Option<String>,
    pub resume_url: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of Candidate for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CandidateSummary {
    pub id: CandidateId,
    pub first_name: String,
    pub last_name: Option<String>,
    pub email: Option<String>,
}

/// Reference to Candidate for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CandidateRef {
    pub id: CandidateId,
}

// ============================================================================
// INTERVIEW TYPES
// ============================================================================

/// Type-safe ID for Interview
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct InterviewId(pub Uuid);

impl InterviewId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for InterviewId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<InterviewId> for Uuid {
    fn from(id: InterviewId) -> Self {
        id.0
    }
}

/// Data transfer object for Interview
///
/// This is the public representation of Interview for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InterviewDto {
    pub id: InterviewId,
    pub company_id: Uuid,
    pub application_id: Uuid,
    pub interviewer_id: Uuid,
    pub scheduled_at: DateTime<Utc>,
    pub round: Option<i32>,
    pub interview_format: Option<String>,
    pub rating: Option<i32>,
    pub feedback: Option<String>,
    pub status: InterviewStatus,
    pub metadata: serde_json::Value,
}

/// Summary view of Interview for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InterviewSummary {
    pub id: InterviewId,
    pub status: InterviewStatus,
}

/// Reference to Interview for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InterviewRef {
    pub id: InterviewId,
}

// ============================================================================
// JOBAPPLICATION TYPES
// ============================================================================

/// Type-safe ID for JobApplication
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct JobApplicationId(pub Uuid);

impl JobApplicationId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for JobApplicationId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<JobApplicationId> for Uuid {
    fn from(id: JobApplicationId) -> Self {
        id.0
    }
}

/// Data transfer object for JobApplication
///
/// This is the public representation of JobApplication for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JobApplicationDto {
    pub id: JobApplicationId,
    pub company_id: Uuid,
    pub candidate_id: Uuid,
    pub requisition_id: Uuid,
    pub status: ApplicationStatus,
    pub applied_at: DateTime<Utc>,
    pub metadata: serde_json::Value,
}

/// Summary view of JobApplication for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JobApplicationSummary {
    pub id: JobApplicationId,
    pub status: ApplicationStatus,
}

/// Reference to JobApplication for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JobApplicationRef {
    pub id: JobApplicationId,
}

// ============================================================================
// JOBOFFER TYPES
// ============================================================================

/// Type-safe ID for JobOffer
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct JobOfferId(pub Uuid);

impl JobOfferId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for JobOfferId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<JobOfferId> for Uuid {
    fn from(id: JobOfferId) -> Self {
        id.0
    }
}

/// Data transfer object for JobOffer
///
/// This is the public representation of JobOffer for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JobOfferDto {
    pub id: JobOfferId,
    pub company_id: Uuid,
    pub application_id: Uuid,
    pub proposed_salary: Option<Decimal>,
    pub employment_type: Option<String>,
    pub status: OfferStatus,
    pub offered_at: Option<DateTime<Utc>>,
    pub accepted_at: Option<DateTime<Utc>>,
    pub metadata: serde_json::Value,
}

/// Summary view of JobOffer for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JobOfferSummary {
    pub id: JobOfferId,
    pub status: OfferStatus,
}

/// Reference to JobOffer for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JobOfferRef {
    pub id: JobOfferId,
}

// ============================================================================
// JOBREQUISITION TYPES
// ============================================================================

/// Type-safe ID for JobRequisition
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct JobRequisitionId(pub Uuid);

impl JobRequisitionId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for JobRequisitionId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<JobRequisitionId> for Uuid {
    fn from(id: JobRequisitionId) -> Self {
        id.0
    }
}

/// Data transfer object for JobRequisition
///
/// This is the public representation of JobRequisition for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JobRequisitionDto {
    pub id: JobRequisitionId,
    pub company_id: Uuid,
    pub department_id: Option<Uuid>,
    pub position_id: Option<Uuid>,
    pub title: String,
    pub headcount: i32,
    pub employment_type: Option<String>,
    pub status: RequisitionStatus,
    pub opened_by: Uuid,
    pub budget: Option<Decimal>,
    pub deadline: Option<NaiveDate>,
    pub metadata: serde_json::Value,
}

/// Summary view of JobRequisition for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JobRequisitionSummary {
    pub id: JobRequisitionId,
    pub title: String,
    pub status: RequisitionStatus,
}

/// Reference to JobRequisition for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JobRequisitionRef {
    pub id: JobRequisitionId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
