//! Recruitment Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;
pub mod exports;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::CandidateService;
pub use application::service::InterviewService;
pub use application::service::JobApplicationService;
pub use application::service::JobOfferService;
pub use application::service::JobRequisitionService;

// Re-exports - Workflows
pub use application::workflows::*;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Recruitment module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let recruitment = RecruitmentModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = recruitment.all_crud_routes();
/// ```
pub struct RecruitmentModule {
    pub(crate) candidate_service: Arc<CandidateService>,
    pub(crate) interview_service: Arc<InterviewService>,
    pub(crate) job_application_service: Arc<JobApplicationService>,
    pub(crate) job_offer_service: Arc<JobOfferService>,
    pub(crate) job_requisition_service: Arc<JobRequisitionService>,
    // <<< CUSTOM FIELDS
    /// The hire write-service (ADR-005 producer): offer→accepted + `recruitment.hired` outbox emit.
    /// Public so the composer / tests can drive hires (`module.job_offer_write_service.hire(id)`).
    pub job_offer_write_service: Arc<application::service::JobOfferWriteService>,
    // END CUSTOM
}

impl RecruitmentModule {
    /// Create a new module builder
    pub fn builder() -> RecruitmentModuleBuilder {
        RecruitmentModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_candidate_routes,
            create_interview_routes,
            create_job_application_routes,
            create_job_offer_routes,
            create_job_requisition_routes,
        };

        Router::new()
            .merge(create_candidate_routes(self.candidate_service.clone()))
            .merge(create_interview_routes(self.interview_service.clone()))
            .merge(create_job_application_routes(self.job_application_service.clone()))
            .merge(create_job_offer_routes(self.job_offer_service.clone()))
            .merge(create_job_requisition_routes(self.job_requisition_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD on every entity; compose a guarded router for production, or call all_crud_routes() for the intentional full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }
}

/// Builder for RecruitmentModule
pub struct RecruitmentModuleBuilder {
    db_pool: Option<PgPool>,
}

impl RecruitmentModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<RecruitmentModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // Candidate service
        let candidate_repository = Arc::new(CandidateRepository::new(db_pool.clone()));
        let candidate_service = Arc::new(CandidateService::with_repository(candidate_repository.clone()));

        // Interview service
        let interview_repository = Arc::new(InterviewRepository::new(db_pool.clone()));
        let interview_service = Arc::new(InterviewService::with_repository(interview_repository.clone()));

        // JobApplication service
        let job_application_repository = Arc::new(JobApplicationRepository::new(db_pool.clone()));
        let job_application_service = Arc::new(JobApplicationService::with_repository(job_application_repository.clone()));

        // JobOffer service
        let job_offer_repository = Arc::new(JobOfferRepository::new(db_pool.clone()));
        let job_offer_service = Arc::new(JobOfferService::with_repository(job_offer_repository.clone()));

        // JobRequisition service
        let job_requisition_repository = Arc::new(JobRequisitionRepository::new(db_pool.clone()));
        let job_requisition_service = Arc::new(JobRequisitionService::with_repository(job_requisition_repository.clone()));

        // <<< CUSTOM
        // ADR-005 producer: bound to the same pool as the repos. `hire()` opens its own tx around the
        // offer-accept + the outbox stage; no shared mutable state, so an Arc is purely for cheap reuse.
        let job_offer_write_service = Arc::new(application::service::JobOfferWriteService::new(db_pool.clone()));
        // END CUSTOM

        Ok(RecruitmentModule {
            candidate_service,
            interview_service,
            job_application_service,
            job_offer_service,
            job_requisition_service,
            // <<< CUSTOM
            job_offer_write_service,
            // END CUSTOM
        })
    }
}

impl Default for RecruitmentModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
