//! Use case type aliases for Candidate aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateCandidateDto, UpdateCandidateDto};
use crate::application::service::CandidateService;
use crate::domain::entity::Candidate;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateCandidateUseCase = CreateUseCase<Candidate, CreateCandidateDto, CandidateService>;
pub type UpdateCandidateUseCase = UpdateUseCase<Candidate, UpdateCandidateDto, CandidateService>;
pub type GetCandidateUseCase    = GetUseCase<Candidate, CandidateService>;
pub type DeleteCandidateUseCase = DeleteUseCase<Candidate, CandidateService>;
pub type ListCandidateUseCase   = ListUseCase<Candidate, CandidateService>;

// <<< CUSTOM
// END CUSTOM
