//! Use case type aliases for Interview aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateInterviewDto, UpdateInterviewDto};
use crate::application::service::InterviewService;
use crate::domain::entity::Interview;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateInterviewUseCase = CreateUseCase<Interview, CreateInterviewDto, InterviewService>;
pub type UpdateInterviewUseCase = UpdateUseCase<Interview, UpdateInterviewDto, InterviewService>;
pub type GetInterviewUseCase    = GetUseCase<Interview, InterviewService>;
pub type DeleteInterviewUseCase = DeleteUseCase<Interview, InterviewService>;
pub type ListInterviewUseCase   = ListUseCase<Interview, InterviewService>;

// <<< CUSTOM
// END CUSTOM
