//! Use case type aliases for JobRequisition aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateJobRequisitionDto, UpdateJobRequisitionDto};
use crate::application::service::JobRequisitionService;
use crate::domain::entity::JobRequisition;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateJobRequisitionUseCase = CreateUseCase<JobRequisition, CreateJobRequisitionDto, JobRequisitionService>;
pub type UpdateJobRequisitionUseCase = UpdateUseCase<JobRequisition, UpdateJobRequisitionDto, JobRequisitionService>;
pub type GetJobRequisitionUseCase    = GetUseCase<JobRequisition, JobRequisitionService>;
pub type DeleteJobRequisitionUseCase = DeleteUseCase<JobRequisition, JobRequisitionService>;
pub type ListJobRequisitionUseCase   = ListUseCase<JobRequisition, JobRequisitionService>;

// <<< CUSTOM
// END CUSTOM
