//! Use case type aliases for JobApplication aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateJobApplicationDto, UpdateJobApplicationDto};
use crate::application::service::JobApplicationService;
use crate::domain::entity::JobApplication;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateJobApplicationUseCase = CreateUseCase<JobApplication, CreateJobApplicationDto, JobApplicationService>;
pub type UpdateJobApplicationUseCase = UpdateUseCase<JobApplication, UpdateJobApplicationDto, JobApplicationService>;
pub type GetJobApplicationUseCase    = GetUseCase<JobApplication, JobApplicationService>;
pub type DeleteJobApplicationUseCase = DeleteUseCase<JobApplication, JobApplicationService>;
pub type ListJobApplicationUseCase   = ListUseCase<JobApplication, JobApplicationService>;

// <<< CUSTOM
// END CUSTOM
