//! Use case type aliases for JobOffer aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateJobOfferDto, UpdateJobOfferDto};
use crate::application::service::JobOfferService;
use crate::domain::entity::JobOffer;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateJobOfferUseCase = CreateUseCase<JobOffer, CreateJobOfferDto, JobOfferService>;
pub type UpdateJobOfferUseCase = UpdateUseCase<JobOffer, UpdateJobOfferDto, JobOfferService>;
pub type GetJobOfferUseCase    = GetUseCase<JobOffer, JobOfferService>;
pub type DeleteJobOfferUseCase = DeleteUseCase<JobOffer, JobOfferService>;
pub type ListJobOfferUseCase   = ListUseCase<JobOffer, JobOfferService>;

// <<< CUSTOM
// END CUSTOM
