//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod candidate_usecases;
pub mod interview_usecases;
pub mod job_application_usecases;
pub mod job_offer_usecases;
pub mod job_requisition_usecases;

pub use candidate_usecases::{
    CreateCandidateUseCase, UpdateCandidateUseCase, GetCandidateUseCase,
    DeleteCandidateUseCase, ListCandidateUseCase,
};
pub use interview_usecases::{
    CreateInterviewUseCase, UpdateInterviewUseCase, GetInterviewUseCase,
    DeleteInterviewUseCase, ListInterviewUseCase,
};
pub use job_application_usecases::{
    CreateJobApplicationUseCase, UpdateJobApplicationUseCase, GetJobApplicationUseCase,
    DeleteJobApplicationUseCase, ListJobApplicationUseCase,
};
pub use job_offer_usecases::{
    CreateJobOfferUseCase, UpdateJobOfferUseCase, GetJobOfferUseCase,
    DeleteJobOfferUseCase, ListJobOfferUseCase,
};
pub use job_requisition_usecases::{
    CreateJobRequisitionUseCase, UpdateJobRequisitionUseCase, GetJobRequisitionUseCase,
    DeleteJobRequisitionUseCase, ListJobRequisitionUseCase,
};

// <<< CUSTOM
// END CUSTOM
