//! HTTP handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod candidate_handler;
pub mod interview_handler;
pub mod job_application_handler;
pub mod job_offer_handler;
pub mod job_requisition_handler;

// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use candidate_handler::{create_candidate_routes, create_candidate_read_routes, create_candidate_write_routes};
pub use interview_handler::{create_interview_routes, create_interview_read_routes, create_interview_write_routes};
pub use job_application_handler::{create_job_application_routes, create_job_application_read_routes, create_job_application_write_routes};
pub use job_offer_handler::{create_job_offer_routes, create_job_offer_read_routes, create_job_offer_write_routes};
pub use job_requisition_handler::{create_job_requisition_routes, create_job_requisition_read_routes, create_job_requisition_write_routes};
// <<< CUSTOM
// END CUSTOM
